create table "sys_access_rule"
(
    "id"             character varying(36) default RANDOM_UUID() not null
        primary key,
    "tenant_id"      character varying(36)                       not null,
    "subsys_code"    character varying(32)                       not null,
    "rule_type"      smallint(16)          default 1             not null,
    "create_user"    character varying(32),
    "create_time"    timestamp(6),
    "update_user"    character varying(32),
    "update_time"    timestamp(6),
    "update_user_id" character varying(36),
    "create_user_id" character varying(36),
    constraint "sys_access_rule_uk"
        unique ("tenant_id", "subsys_code")
);

create table "sys_access_rule_ip"
(
    "id"              character varying(36) default RANDOM_UUID() not null
        primary key,
    "rule_id"         character varying(36)                       not null,
    "ip_start"        bigint(64)                                  not null,
    "ip_end"          bigint(64)                                  not null,
    "ip_type"         smallint(16)                                not null,
    "expiration_date" timestamp(6)                                not null,
    "create_user"     character varying(32),
    "create_time"     timestamp(6),
    "update_user"     character varying(32),
    "update_time"     timestamp(6),
    "remark"          character varying(128),
    "update_user_id"  character varying(36),
    "create_user_id"  character varying(36),
    "active"          boolean               default TRUE          not null,
    "is_deleted"      boolean               default FALSE         not null
);

create table "sys_app"
(
    "id"              character varying(36) default RANDOM_UUID() not null
        primary key,
    "app_name"        character varying(64)                       not null,
    "protocol"        character varying(10)                       not null,
    "ip"              character varying(128)                      not null,
    "port"            smallint(16)                                not null,
    "frequency"       smallint(16)          default 1,
    "status"          character varying(32) default 'active',
    "last_heart_time" timestamp(6)          default LOCALTIMESTAMP
);

create table "sys_cache"
(
    "id"             character varying(36) default RANDOM_UUID() not null
        primary key,
    "name"           character varying(64)                       not null,
    "server_code"    character varying(32)                       not null,
    "strategy_code"  character varying(16)                       not null,
    "write_on_boot"  boolean               default FALSE         not null,
    "write_in_time"  boolean               default FALSE         not null,
    "ttl"            integer(32),
    "remark"         character varying(500),
    "active"         boolean               default TRUE          not null,
    "built_in"       boolean               default FALSE         not null,
    "create_user"    character varying(36),
    "create_time"    timestamp(6)          default LOCALTIMESTAMP,
    "update_user"    character varying(36),
    "update_time"    timestamp(6),
    "update_user_id" character(36),
    "create_user_id" character(36)
);

create unique index "uq_sys_cache"
    on "sys_cache" ("name");

create table "sys_datasource"
(
    "id"              integer(32) generated by default as identity (maxvalue 2147483647)
        primary key,
    "name"            character varying(32),
    "ds_use"          character varying(32)                    not null,
    "url"             character varying(256),
    "username"        character varying(32)                    not null,
    "password"        character varying(128)                   not null,
    "remark"          character varying(128),
    "active"          boolean                                  not null,
    "built_in"        boolean,
    "create_user"     character varying(36),
    "create_time"     timestamp(6),
    "update_user"     character varying(36),
    "update_time"     timestamp(6),
    "extend_property" character large object(max),
    "ds_type"         character varying(32) default 'hikariCP' not null,
    "update_user_id"  character varying(36),
    "create_user_id"  character varying(36)
);


create table "sys_domain"
(
    "id"             integer(32) generated by default as identity (maxvalue 2147483647)
        primary key,
    "domain"         character varying(100),
    "is_enable"      boolean,
    "is_deleted"     boolean,
    "subsys_code"    character varying(32),
    "create_user"    character varying(32),
    "create_time"    timestamp(6),
    "update_user"    character varying(32),
    "update_time"    timestamp(6),
    "build_in"       boolean,
    "tenant_id"      character varying(36) not null,
    "remark"         character varying(128),
    "update_user_id" character varying(36),
    "create_user_id" character varying(36),
    "type"           character varying(10),
    "language"       character varying(10)
);

create unique index "sys_domain_uniq"
    on "sys_domain" ("domain", "is_deleted");

create table "sys_i18n"
(
    "id"          character varying(36) default RANDOM_UUID() not null
        primary key,
    "locale"      character varying(8)                        not null,
    "i18n_module" character varying(32)                       not null,
    "i18n_type"   character varying(32)                       not null,
    "i18n_key"    character varying(128)                      not null,
    "i18n_value"  character varying(1000)                     not null,
    "active"      boolean               default TRUE          not null,
    "built_in"    boolean               default FALSE         not null,
    "trans"       boolean               default FALSE         not null
);

comment on column "sys_i18n"."locale" is '语言_地区';

comment on column "sys_i18n"."i18n_type" is '国际化类型[validation\errors\params]';

comment on column "sys_i18n"."i18n_key" is '国际化key';

comment on column "sys_i18n"."i18n_value" is '国际化值';

comment on column "sys_i18n"."active" is '是否启用';

comment on column "sys_i18n"."built_in" is '是否内置';

comment on column "sys_i18n"."trans" is '是否翻译';

create index "idx_sys_i18n_locale_i18n_module_i18n_type"
    on "sys_i18n" ("locale", "i18n_module", "i18n_type");

create unique index "uk_sys_i18n_locale_i18n_module_i18n_type_i18n_key"
    on "sys_i18n" ("locale", "i18n_module", "i18n_type", "i18n_key");

create table "sys_language"
(
    "lang_code"      character varying(64)     not null,
    "display_name"   character varying(200)    not null,
    "remark"         character varying(500),
    "active"         boolean      default TRUE not null,
    "create_user"    character varying(36),
    "create_time"    timestamp(6) default LOCALTIMESTAMP,
    "update_user"    character varying(36),
    "update_time"    timestamp(6),
    "update_user_id" character varying(36),
    "create_user_id" character varying(36),
    constraint "sys_language_pk"
        primary key ("lang_code")
);

create table "sys_module"
(
    "id"          integer(32) generated by default as identity (maxvalue 2147483647)
        primary key,
    "subsys_code" character varying(32)  not null,
    "module_code" character varying(100) not null,
    "module_name" character varying(200) not null,
    "parent_id"   integer(32),
    "is_tenant"   boolean default TRUE   not null,
    constraint "sys_module_un"
        unique ("subsys_code", "module_code")
);

create table "sys_param"
(
    "id"             integer(32) generated by default as identity (maxvalue 2147483647)
        primary key,
    "module_id"      character varying(100),
    "param_type"     character varying(32) not null,
    "param_code"     character varying(32) not null,
    "param_value"    character large object(max),
    "default_value"  character large object(max),
    "order_num"      integer(32),
    "remark"         character varying(128),
    "parent_code"    character varying(32),
    "active"         boolean default TRUE  not null,
    "subsys_code"    character varying(32),
    "tenant_id"      character varying(36) not null,
    "create_user"    character varying(32),
    "create_time"    timestamp(6),
    "update_user"    character varying(32),
    "update_time"    timestamp(6),
    "update_user_id" character varying(36),
    "create_user_id" character varying(36),
    "description"    character varying(256)
);

create table "sys_resource"
(
    "id"             integer(32) generated by default as identity (maxvalue 2147483647)
        primary key,
    "name"           character varying(64) not null,
    "url"            character varying(128),
    "parent_id"      integer(32),
    "sort_num"       integer(32),
    "remark"         character varying(255),
    "subsys_code"    character varying(32) not null,
    "permission"     character varying(64),
    "resource_type"  integer(32)           not null,
    "icon"           character varying(255),
    "privilege"      boolean default FALSE,
    "built_in"       boolean default FALSE,
    "status"         boolean default FALSE,
    "create_user_id" character varying(36),
    "create_user"    character varying(32),
    "create_time"    timestamp(6),
    "update_user_id" character varying(36),
    "update_user"    character varying(32),
    "update_time"    timestamp(6)
);

create index "fk_sys_resource_parent_id"
    on "sys_resource" ("parent_id");

create table "sys_server_info"
(
    "code"           character varying(32)  not null,
    "name"           character varying(200) not null,
    "create_time"    timestamp(6),
    "create_user"    character varying(200),
    "update_time"    timestamp(6),
    "update_user"    character varying(200),
    "built_in"       boolean default FALSE,
    "update_user_id" character varying(36),
    "create_user_id" character varying(36),
    "context"        character varying(100) not null,
    "remark"         character varying(400),
    "atomic"         boolean,
    "active"         boolean                not null,
    constraint "sys_service_info_pk"
        primary key ("code")
);

create table "sys_sub_system"
(
    "code"           character varying(32)  not null
        primary key,
    "name"           character varying(200) not null
        constraint "sys_sub_system_un"
            unique,
    "create_time"    timestamp(6),
    "create_user"    character varying(200),
    "update_time"    timestamp(6),
    "update_user"    character varying(200),
    "active"         boolean default TRUE   not null,
    "built_in"       boolean default FALSE,
    "update_user_id" character varying(36),
    "create_user_id" character varying(36),
    "server_code"    character large object(max)
);

create table "sys_sub_system_server"
(
    "id"          character(36) default RANDOM_UUID() not null,
    "subsys_code" character varying(36)               not null,
    "server_code" character varying(36)               not null
);

create table "sys_tenant"
(
    "id"               character varying(36) default RANDOM_UUID() not null
        primary key,
    "name"             character varying(200)                      not null
        constraint "sys_tenant_un"
            unique,
    "timezone"         character varying(16),
    "default_language" character varying(64),
    "create_time"      timestamp(6)                                not null,
    "create_user"      character varying(200)                      not null,
    "update_time"      timestamp(6)                                not null,
    "update_user"      character varying(200)                      not null,
    "active"           boolean               default TRUE          not null,
    "built_in"         boolean               default FALSE,
    "update_user_id"   character varying(36),
    "create_user_id"   character varying(36),
    "remark"           character varying(400)
);

create table "sys_tenant_datasource"
(
    "id"            character varying(36) default RANDOM_UUID() not null,
    "datasource_id" integer(32)                                 not null,
    "tenant_id"     character varying(36)                       not null,
    "server_code"   character varying(36),
    "mode"          character varying(10)
);

create index "sys_tenant_datasource_tenant_id_idx"
    on "sys_tenant_datasource" ("tenant_id");

create table "sys_tenant_language"
(
    "id"         character(36) default RANDOM_UUID() not null,
    "tenant_id"  character varying(36)               not null,
    "lang_code"  character varying(64)               not null,
    "is_default" boolean,
    constraint "sys_tenant_language_pk"
        primary key ("id")
);

create table "sys_tenant_resource"
(
    "id"          character(36) default RANDOM_UUID() not null
        primary key,
    "tenant_id"   character varying(36),
    "resource_id" integer(32)
);

create table "sys_tenant_sub_system"
(
    "id"             integer(32) generated by default as identity (maxvalue 2147483647)
        primary key,
    "subsys_code"    character varying(32)  not null,
    "tenant_id"      character varying(36)  not null,
    "create_time"    timestamp(6)           not null,
    "create_user"    character varying(200) not null,
    "update_time"    timestamp(6)           not null,
    "update_user"    character varying(200) not null,
    "update_user_id" character varying(36),
    "create_user_id" character varying(36)
);



CREATE FORCE VIEW "v_sys_domain"
            ("domain", "tenant_id", "subsys_code", "tenant_name", "timezone", "locale", "type") AS
SELECT "sd"."domain",
       "sd"."tenant_id",
       "sd"."subsys_code",
       "st"."name"                                        AS "tenant_name",
       "st"."timezone",
       COALESCE("sd"."language", "st"."default_language") AS "locale",
       "sd"."type"
FROM "sys_domain" "sd"
         LEFT OUTER JOIN "sys_tenant" "st"
                         ON "sd"."tenant_id" = "st"."id"
WHERE ("sd"."is_deleted" = FALSE)
  AND ("is_enable" = TRUE);

CREATE FORCE VIEW "v_sys_param"
            ("id", "module_id", "param_type", "param_code", "param_value", "default_value", "order_num", "remark",
             "parent_code", "active", "subsys_code", "tenant_id", "create_user", "create_time", "update_user",
             "update_time", "update_user_id", "create_user_id", "module_code", "module_name")
AS
SELECT "sp"."id",
       "sp"."module_id",
       "sp"."param_type",
       "sp"."param_code",
       "sp"."param_value",
       "sp"."default_value",
       "sp"."order_num",
       "sp"."remark",
       "sp"."parent_code",
       "sp"."active",
       "sp"."subsys_code",
       "sp"."tenant_id",
       "sp"."create_user",
       "sp"."create_time",
       "sp"."update_user",
       "sp"."update_time",
       "sp"."update_user_id",
       "sp"."create_user_id",
       "sp"."module_id" AS "module_code",
       "sp"."module_id" AS "module_name"
FROM "sys_param" "sp";

CREATE FORCE VIEW "v_sys_tenant_datasource"
            ("server_code", "tenant_id", "server_name", "datasource_id", "datasource_name", "readonly_datasource_id",
             "readonly_datasource_name")
AS
SELECT "foo"."server_code",
       "foo"."tenant_id",
       "foo"."server_name",
       "foo"."datasource_id",
       (SELECT "sd"."name"
        FROM "sys_datasource" "sd"
        WHERE "sd"."id" = "foo"."datasource_id")          AS "datasource_name",
       "foo"."readonly_datasource_id",
       (SELECT "sd"."name"
        FROM "sys_datasource" "sd"
        WHERE "sd"."id" = "foo"."readonly_datasource_id") AS "readonly_datasource_name"
FROM (SELECT DISTINCT "ssss"."server_code",
                      "stss"."tenant_id",
                      (SELECT "ssi"."name"
                       FROM "sys_server_info" "ssi"
                       WHERE CAST("ssi"."code" AS CHARACTER LARGE OBJECT) =
                             CAST("ssss"."server_code" AS CHARACTER LARGE OBJECT)) AS "server_name",
                      (SELECT "std"."datasource_id"
                       FROM "sys_tenant_datasource" "std"
                       WHERE (CAST("ssss"."server_code" AS CHARACTER LARGE OBJECT) =
                              CAST("std"."server_code" AS CHARACTER LARGE OBJECT))
                         AND ("std"."mode" = 'master')
                         AND (CAST("std"."tenant_id" AS CHARACTER LARGE OBJECT) =
                              CAST("stss"."tenant_id" AS CHARACTER LARGE OBJECT))) AS "datasource_id",
                      (SELECT "std"."datasource_id"
                       FROM "sys_tenant_datasource" "std"
                       WHERE (CAST("ssss"."server_code" AS CHARACTER LARGE OBJECT) =
                              CAST("std"."server_code" AS CHARACTER LARGE OBJECT))
                         AND ("std"."mode" = 'readonly')
                         AND (CAST("std"."tenant_id" AS CHARACTER LARGE OBJECT) =
                              CAST("stss"."tenant_id" AS CHARACTER LARGE OBJECT))) AS "readonly_datasource_id"
      FROM "sys_tenant_sub_system" "stss"
               INNER JOIN "sys_sub_system_server" "ssss"
                          ON 1 = 1
               INNER JOIN "sys_server_info" "ssi2"
                          ON 1 = 1
      WHERE (CAST("ssi2"."code" AS CHARACTER LARGE OBJECT) = CAST("ssss"."server_code" AS CHARACTER LARGE OBJECT))
        AND ("ssi2"."atomic" = FALSE)
        AND (CAST("stss"."subsys_code" AS CHARACTER LARGE OBJECT) =
             CAST("ssss"."subsys_code" AS CHARACTER LARGE OBJECT))) "foo";



