package io.kudos.base.security

import io.kudos.base.lang.string.EncodeKit
import io.kudos.base.logger.LogFactory
import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.Mac
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Cryptography utility class.
 *
 * Supports HMAC-SHA1 message signing and AES symmetric encryption.
 * Supports both Hex and Base64 encodings (this class mainly exposes Hex).
 *
 * **AES note**: newly produced ciphertext uses **AES-128-GCM** (random IV, authenticated encryption). The read path
 * still supports legacy **AES/ECB** and historical **SHA1PRNG-derived key** data for backward compatibility with
 * existing stored data.
 *
 * @author K
 * @since 1.0.0
 */
object CryptoKit {

    /** Logger used to record warnings such as fallback decryption failures on the compatibility path. */
    private val logger = LogFactory.getLog(this::class)

    /** AES algorithm name. */
    private const val AES_ALGORITHM = "AES"
    /** Equivalent in behavior to the historical `Cipher.getInstance("AES")`, written out explicitly for clarity. */
    private const val AES_ECB_TRANSFORM = "AES/ECB/PKCS5Padding"
    /** AES-GCM authenticated-encryption transformation name, with no padding. */
    private const val AES_GCM_TRANSFORM = "AES/GCM/NoPadding"
    /** HMAC-SHA1 algorithm name. */
    private const val HMACSHA1 = "HmacSHA1"
    /** Key prefix that triggers "ciphertext case flipping" (kept for backward compatibility with the old convention). */
    private const val HTB = "_HTB"

    /** Ciphertext marker prefix used by the no-arg form of [aesEncrypt]/[aesDecrypt] to distinguish legacy plaintext from encrypted content. */
    private const val PREFIX = "┼"
    /** Charset used for conversion between strings and bytes. */
    private const val CHARSET = "UTF-8"

    /** Default HMAC-SHA1 key length (RFC2401 recommended value). */
    private const val DEFAULT_HMACSHA1_KEYSIZE = 160 // RFC2401

    /** Default byte size of the random IV generated by [generateIV] (matches the AES block size). */
    private const val DEFAULT_IVSIZE = 16

    /** New-format ciphertext prefix: ASCII "GCM" + version byte 0x01. */
    private val AES_GCM_MAGIC = byteArrayOf(0x47, 0x43, 0x4D, 0x01)

    /** GCM mode IV length (NIST recommends 12 bytes). */
    private const val GCM_IV_LENGTH = 12
    /** GCM authentication tag length (bits); 128 bits is the standard length. */
    private const val GCM_TAG_LENGTH_BITS = 128

    /** Lowercase character table used for Hex encoding. */
    private val DIGITS = charArrayOf(
        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'
    )

    /** Strong random source used for IV and key generation. */
    private val random = SecureRandom()

    //-- HMAC-SHA1 function --//
    /**
     * Signs a message using HMAC-SHA1; returns a byte array of length 20 bytes.
     *
     * @param input the original input byte array
     * @param key   the HMAC-SHA1 key
     * @return the signed byte array
     * @author K
     * @since 1.0.0
     */
    fun hmacSha1(input: ByteArray, key: ByteArray): ByteArray {
        val secretKey = SecretKeySpec(key, HMACSHA1)
        val mac = Mac.getInstance(HMACSHA1)
        mac.init(secretKey)
        return mac.doFinal(input)
    }

    /**
     * Verifies whether an HMAC-SHA1 signature is correct.
     *
     * @param expected the existing signature
     * @param input    the original input string
     * @param key      the key
     * @return true if the HMAC-SHA1 signature is correct
     * @author K
     * @since 1.0.0
     */
    fun isMacValid(expected: ByteArray, input: ByteArray, key: ByteArray): Boolean {
        val actual = hmacSha1(input, key)
        return expected.contentEquals(actual)
    }

    /**
     * Generates an HMAC-SHA1 key; returns a byte array of 160 bits (20 bytes).
     * The HMAC-SHA1 algorithm has no special requirements for the key; RFC2401 recommends a minimum length of 160 bits (20 bytes).
     *
     * @return the HMAC-SHA1 key
     * @author K
     * @since 1.0.0
     */
    fun generateHmacSha1Key(): ByteArray {
        val keyGenerator = KeyGenerator.getInstance(HMACSHA1)
        keyGenerator.init(DEFAULT_HMACSHA1_KEYSIZE)
        val secretKey = keyGenerator.generateKey()
        return secretKey.encoded
    }

    //region AES
    /**
     * Encrypts the original string using AES-GCM and returns its hexadecimal representation (contains a magic prefix and IV; **not** the legacy ECB format).
     *
     * @param input    the original input string
     * @param password the key string
     * @return the encrypted string (in hexadecimal representation)
     * @author K
     * @since 1.0.0
     */
    fun aesEncrypt(input: String, password: String): String {
        val plain = input.toByteArray(charset(CHARSET))
        val passwordBytes = password.toByteArray(charset(CHARSET))
        val packed = aesGcmEncrypt(plain, passwordBytes)
        return aesEncryptBytes(packed, password)
    }

    /**
     * Decrypts a byte array encrypted with AES (auto-detects the new GCM format and the legacy ECB/SHA1PRNG format).
     *
     * @param content  the AES-encrypted byte array
     * @param password the key used at encryption time
     * @return the byte array of the original string
     * @author K
     * @since 1.0.0
     */
    fun aesDecrypt(content: ByteArray, password: String): ByteArray {
        val passwordBytes = password.toByteArray(charset(CHARSET))
        if (content.size >= AES_GCM_MAGIC.size &&
            content.copyOfRange(0, AES_GCM_MAGIC.size).contentEquals(AES_GCM_MAGIC)
        ) {
            return aesGcmDecrypt(content, passwordBytes)
        }
        return runCatching {
            aesEcb(content, passwordBytes, Cipher.DECRYPT_MODE)
        }.getOrElse {
            // Backward compatibility: fallback for historical SHA1PRNG-derived data.
            aesLegacy(content, passwordBytes, Cipher.DECRYPT_MODE)
        }
    }

    /**
     * Encrypts plaintext using AES-128-GCM.
     * A random 12-byte IV is generated each time; the output format is `AES_GCM_MAGIC || IV || ciphertext+tag`.
     *
     * @param plain the plaintext bytes to encrypt
     * @param password password bytes; derived to a 128-bit key via [buildAesKey]
     * @return the ciphertext byte array with the magic prefix and IV
     * @author K
     * @since 1.0.0
     */
    private fun aesGcmEncrypt(plain: ByteArray, password: ByteArray): ByteArray {
        val iv = ByteArray(GCM_IV_LENGTH)
        random.nextBytes(iv)
        val cipher = Cipher.getInstance(AES_GCM_TRANSFORM)
        cipher.init(Cipher.ENCRYPT_MODE, buildAesKey(password), GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv))
        val ct = cipher.doFinal(plain)
        return AES_GCM_MAGIC + iv + ct
    }

    /**
     * Decrypts the GCM ciphertext produced by [aesGcmEncrypt].
     * The input is expected to start with [AES_GCM_MAGIC], followed by a 12-byte IV, then the ciphertext and authentication tag.
     *
     * @param input the GCM ciphertext containing the magic and IV
     * @param password password bytes; must match those used at encryption time
     * @return the decrypted plaintext byte array
     * @throws IllegalArgumentException when the input is too short to contain the magic and IV
     * @author K
     * @since 1.0.0
     */
    private fun aesGcmDecrypt(input: ByteArray, password: ByteArray): ByteArray {
        val headerLen = AES_GCM_MAGIC.size + GCM_IV_LENGTH
        require(input.size > headerLen) { "Invalid AES-GCM payload length" }
        val iv = input.copyOfRange(AES_GCM_MAGIC.size, headerLen)
        val ct = input.copyOfRange(headerLen, input.size)
        val cipher = Cipher.getInstance(AES_GCM_TRANSFORM)
        cipher.init(Cipher.DECRYPT_MODE, buildAesKey(password), GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv))
        return cipher.doFinal(ct)
    }

    /**
     * AES/ECB/PKCS5Padding encryption/decryption (legacy compatibility path).
     * Used only for reading historical data; should not be used for encrypting new data.
     *
     * @param input the data to process
     * @param password password bytes; derived to a 128-bit key via [buildAesKey]
     * @param mode [Cipher.ENCRYPT_MODE] or [Cipher.DECRYPT_MODE]
     * @return the processed byte array
     * @author K
     * @since 1.0.0
     */
    private fun aesEcb(input: ByteArray, password: ByteArray, mode: Int): ByteArray {
        val cipher = Cipher.getInstance(AES_ECB_TRANSFORM)
        cipher.init(mode, buildAesKey(password))
        return cipher.doFinal(input)
    }

    /**
     * Oldest key-derivation path: generates a 128-bit key using SHA1PRNG with the password as the seed.
     * Used only as a fallback when [aesEcb] direct decryption fails, to read the earliest stored ciphertext.
     *
     * @param input the data to decrypt
     * @param password password bytes, used as the SHA1PRNG seed
     * @param mode [Cipher.ENCRYPT_MODE] or [Cipher.DECRYPT_MODE]
     * @return the processed byte array
     * @author K
     * @since 1.0.0
     */
    private fun aesLegacy(input: ByteArray, password: ByteArray, mode: Int): ByteArray {
        val generator = KeyGenerator.getInstance(AES_ALGORITHM)
        val secureRandom = SecureRandom.getInstance("SHA1PRNG")
        secureRandom.setSeed(password)
        generator.init(128, secureRandom)
        val cipher = Cipher.getInstance(AES_ECB_TRANSFORM)
        cipher.init(mode, generator.generateKey())
        return cipher.doFinal(input)
    }

    /**
     * Hashes the password once with SHA-256 and takes the first 16 bytes as the AES-128 key.
     * This both ensures a valid key length and avoids exposing the password bytes directly.
     *
     * @param password the original password bytes
     * @return an AES key suitable for direct use with [Cipher.init]
     * @author K
     * @since 1.0.0
     */
    private fun buildAesKey(password: ByteArray): SecretKeySpec {
        val digest = MessageDigest.getInstance("SHA-256").digest(password)
        val key = digest.copyOf(16) // AES-128
        return SecretKeySpec(key, AES_ALGORITHM)
    }

    /**
     * Decrypts an AES-encrypted, hex-encoded string.
     *
     * Relationship with [tryAesDecrypt]: this method logs a warning and returns an empty string on decryption failure
     * to preserve historical call semantics. Use [tryAesDecrypt] if you need to distinguish failure from empty plaintext.
     *
     * @param contentHex the AES-encrypted, hex-encoded string
     * @param password   the key used at encryption time
     * @return the original string; returns `""` on decryption failure
     * @author K
     * @since 1.0.0
     */
    fun aesDecrypt(contentHex: String, password: String): String {
        return tryAesDecrypt(contentHex, password).getOrElse {
            logger.warn("AES decrypt failed, returning empty string for compatibility: {0}", it.message)
            ""
        }
    }

    /**
     * Decrypts an AES-encrypted, hex-encoded string, returning [Result] to make the failure semantics explicit.
     *
     * @param contentHex the AES-encrypted, hex-encoded string
     * @param password   the key used at encryption time
     * @return the plaintext string on success; otherwise the wrapped exception
     */
    fun tryAesDecrypt(contentHex: String, password: String): Result<String> {
        return runCatching {
            val bytes = aesDecryptBytes(contentHex, password)
            val result = aesDecrypt(bytes, password)
            String(result, charset(CHARSET))
        }
    }

    /**
     * Encrypts the original string with AES and returns its hexadecimal representation (with a [PREFIX] prefix; the inner payload is GCM ciphertext).
     *
     * @param input the original input string
     * @return the encrypted string (in hexadecimal representation)
     * @author K
     * @since 1.0.0
     */
    fun aesEncrypt(input: String): String = PREFIX + aesEncrypt(input, CryptoKey.KEY_DEFAULT)

    /**
     * Decrypts an AES-encrypted, hex-encoded string, with backward compatibility for unencrypted historical data.
     *
     * @param contentHex the AES-encrypted, hex-encoded string
     * @return the original string
     * @author K
     * @since 1.0.0
     */
    fun aesDecrypt(contentHex: String): String {
        return if (contentHex.startsWith(PREFIX)) { // encrypted
            val content = contentHex.removePrefix(PREFIX)
            aesDecrypt(content, CryptoKey.KEY_DEFAULT)
        } else { // unencrypted historical data
            contentHex
        }
    }

    //endregion

    /**
     * Generates a random IV; default size is cipher.getBlockSize() (16 bytes).
     *
     * @return the IV as a byte array
     * @author K
     * @since 1.0.0
     */
    fun generateIV(): ByteArray {
        val bytes = ByteArray(DEFAULT_IVSIZE)
        random.nextBytes(bytes)
        return bytes
    }

    /**
     * Encodes the byte array as a hexadecimal character array.
     *
     * @param data the byte array
     * @return the character array in hexadecimal representation
     * @author K
     * @since 1.0.0
     */
    fun encodeHex(data: ByteArray): CharArray {
        val l = data.size
        val out = CharArray(l shl 1)
        // two characters form the hex value.
        var i = 0
        var j = 0
        while (i < l) {
            out[j++] = DIGITS[0xF0 and data[i].toInt() ushr 4]
            out[j++] = DIGITS[0x0F and data[i].toInt()]
            i++
        }
        return out
    }

    /**
     * Decodes a hex-encoded byte array (input is the byte representation of ASCII hex characters, e.g. UTF-8 `0-9a-fA-F`).
     *
     * @param bytes the hex-encoded byte array
     * @return the decoded byte array
     * @author K
     * @since 1.0.0
     */
    fun decodeHex(bytes: ByteArray): ByteArray {
        val iLen = bytes.size
        require(iLen % 2 == 0) { "Hex string length must be even, got $iLen" }
        val arrOut = ByteArray(iLen / 2)
        var i = 0
        var o = 0
        while (i < iLen) {
            val hi = hexNibble(bytes[i])
            val lo = hexNibble(bytes[i + 1])
            arrOut[o++] = ((hi shl 4) or lo).toByte()
            i += 2
        }
        return arrOut
    }

    /**
     * Converts a single-byte ASCII hex character (`0-9`, `a-f`, `A-F`) to an integer 0..15.
     *
     * @param b the byte representation of an ASCII hex character
     * @return the decimal value of the character
     * @throws NumberFormatException when the byte is not a valid hex character
     * @author K
     * @since 1.0.0
     */
    private fun hexNibble(b: Byte): Int {
        val c = b.toInt() and 0xFF
        return when {
            c in 48..57 -> c - 48
            c in 97..102 -> c - 97 + 10
            c in 65..70 -> c - 65 + 10
            else -> throw NumberFormatException("Invalid hex digit: $c")
        }
    }

    /**
     * Determines the decryption mode: flip case.
     *
     * @param input
     * @param password
     * @return
     */
    private fun aesDecryptBytes(input: String, password: String): ByteArray {
        return if (password.isNotBlank() && password.startsWith(HTB)) {
            EncodeKit.decodeHex(input.lowercase())
        } else {
            EncodeKit.decodeHex(input)
        }
    }

    /**
     * Determines the encryption mode: flip case.
     *
     * @param bytes
     * @param password
     * @return
     */
    private fun aesEncryptBytes(bytes: ByteArray, password: String): String {
        return if (password.isNotBlank() && password.startsWith(HTB)) {
            EncodeKit.encodeHex(bytes).uppercase()
        } else {
            EncodeKit.encodeHex(bytes)
        }
    }

}
