kudos:
  ability:
    distributed:
      stream:
        rocketmq:
          batch-consumer:
            deserialization-filter: ${ROCKETMQ_BATCH_CONSUMER_DESERIALIZATION_FILTER:}

spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: ${ROCKETMQ_NAME_SERVER:localhost:9876}
