spring:
  application:
    name: kudos-ms-tag-api-admin
  datasource:
    dynamic:
      primary: h2
      datasource:
        h2:
          driver-class-name: org.h2.Driver
          url: jdbc:h2:~/h2/tag;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
          username: sa
          password: sa

kudos:
  ability:
    flyway:
      datasource-config:
        h2: tag
