drop TABLE IF EXISTS "test_table_ktorm";
CREATE TABLE IF NOT EXISTS "test_table_ktorm"
(
    "id"            int2 not null,
    "name"          varchar(255) NOT NULL,
    "birthday"      timestamp(6),
    "active" bool,
    "weight"        float8,
    "height"        int2,
    CONSTRAINT "pk_test_table_ktorm" PRIMARY KEY ("id")
);

comment on table "test_table_ktorm" is '测试表';
COMMENT ON COLUMN "test_table_ktorm"."id" IS '主键';
COMMENT ON COLUMN "test_table_ktorm"."name" IS '名字';
COMMENT ON COLUMN "test_table_ktorm"."birthday" IS '生日';
COMMENT ON COLUMN "test_table_ktorm"."active" IS '是否生效';
COMMENT ON COLUMN "test_table_ktorm"."weight" IS '体重';
COMMENT ON COLUMN "test_table_ktorm"."height" IS '身高';

drop TABLE IF EXISTS "test_built_in_ktorm";
CREATE TABLE IF NOT EXISTS "test_built_in_ktorm"
(
    "id"       int2         not null,
    "name"     varchar(255) NOT NULL,
    "built_in" bool         not null,
    CONSTRAINT "pk_test_built_in_ktorm" PRIMARY KEY ("id")
);

COMMENT ON TABLE "test_built_in_ktorm" IS '带内置标记的测试表';
COMMENT ON COLUMN "test_built_in_ktorm"."id" IS '主键';
COMMENT ON COLUMN "test_built_in_ktorm"."name" IS '名称';
COMMENT ON COLUMN "test_built_in_ktorm"."built_in" IS '是否内置';

drop TABLE IF EXISTS "test_managed_ktorm";
CREATE TABLE IF NOT EXISTS "test_managed_ktorm"
(
    "id"               varchar(36)  not null,
    "name"             varchar(255),
    "create_time"      timestamp(6),
    "create_user_id"   varchar(36),
    "create_user_name" varchar(64),
    "update_time"      timestamp(6),
    "update_user_id"   varchar(36),
    "update_user_name" varchar(64),
    "active"           bool,
    "built_in"         bool,
    "remark"           varchar(255),
    CONSTRAINT "pk_test_managed_ktorm" PRIMARY KEY ("id")
);

COMMENT ON TABLE "test_managed_ktorm" IS '带管理字段的测试表（审计字段自动填充用）';

drop TABLE IF EXISTS "test_auto_inc_ktorm";
CREATE TABLE IF NOT EXISTS "test_auto_inc_ktorm"
(
    "id"   int GENERATED BY DEFAULT AS IDENTITY not null,
    "name" varchar(255),
    CONSTRAINT "pk_test_auto_inc_ktorm" PRIMARY KEY ("id")
);

COMMENT ON TABLE "test_auto_inc_ktorm" IS '自增主键测试表（不带 id 插入用）';