package io.kudos.ability.data.rdb.ktorm.support

import io.kudos.ability.data.rdb.ktorm.datasource.currentDatabase
import io.kudos.ability.data.rdb.ktorm.rowscope.RowScopeEnforcer
import io.kudos.base.bean.BeanKit
import io.kudos.base.logger.LogFactory
import io.kudos.base.lang.string.underscoreToHump
import io.kudos.base.query.Criteria
import io.kudos.base.query.PagingSearchResult
import io.kudos.base.query.enums.OperatorEnum
import io.kudos.base.query.sort.Order
import io.kudos.base.query.sort.sortablePropertyNamesForEntity
import io.kudos.base.support.GroupExecutor
import io.kudos.base.support.dao.IBaseReadOnlyDao
import io.kudos.base.support.logic.AndOrEnum
import io.kudos.base.model.payload.ISearchPayload
import io.kudos.base.model.payload.ListSearchPayload
import io.kudos.base.model.payload.MutableListSearchPayload
import io.kudos.context.core.KudosContextHolder
import org.ktorm.database.Database
import org.ktorm.dsl.*
import org.ktorm.entity.*
import org.ktorm.expression.InListExpression
import org.ktorm.expression.OrderByExpression
import org.ktorm.schema.Column
import org.ktorm.schema.ColumnDeclaring
import org.ktorm.schema.Table
import java.util.concurrent.ConcurrentHashMap
import kotlin.reflect.KClass
import kotlin.reflect.KParameter
import kotlin.reflect.KProperty1
import kotlin.reflect.KType
import kotlin.reflect.KTypeParameter
import kotlin.reflect.full.isSubclassOf
import kotlin.reflect.full.memberProperties
import kotlin.reflect.full.primaryConstructor

/**
 * Base read-only data access object that encapsulates common query operations for a database table.
 *
 * @param PK Entity primary key type
 * @param E Entity type
 * @param T Type of the database table-entity binding object
 * @author K
 * @author AI: Codex
 * @author AI: Claude
 * @since 1.0.0
 */
open class BaseReadOnlyDao<PK : Any, E : IDbEntity<PK, E>, T : Table<E>> : IBaseReadOnlyDao<PK, E> {

    /** Database table-entity binding object */
    private var table: T? = null

    private var entityClass: KClass<E>? = null

    /**
     * Returns the database table-entity binding object.
     *
     * @return Database table-entity binding object
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    @Suppress("UNCHECKED_CAST")
    protected fun table(): T {
        if (table == null) {
            val tableClass = daoTypeArgument(TABLE_TYPE_ARGUMENT) as KClass<T>
            table = requireNotNull(tableClass.objectInstance) {
                "DAO generic table type [${tableClass.qualifiedName}] must be an object singleton."
            }
        }
        return requireNotNull(table) { "Failed to initialize the table object corresponding to the DAO." }
    }

    /**
     * Returns the entity type corresponding to the current DAO.
     *
     * @return Entity KClass
     */
    @Suppress("UNCHECKED_CAST")
    protected fun entityClass(): KClass<E> {
        if (entityClass == null) {
            entityClass = daoTypeArgument(ENTITY_TYPE_ARGUMENT) as KClass<E>
        }
        return requireNotNull(entityClass) { "Failed to resolve the entity type corresponding to the DAO." }
    }

    /**
     * The concrete class this DAO passes to [BaseReadOnlyDao] as its [index]-th type argument.
     *
     * Walks the whole supertype chain and substitutes type variables on the way up, rather than
     * reading the type arguments off the direct superclass. That distinction is the difference
     * between working and not for two shapes that both show up in practice:
     *
     * - **an intermediate abstract DAO** — the natural way to give a family of tables a shared
     *   method: `abstract class AbstractTenantDao<E : IDbEntity<String, E>, T : Table<E>> :
     *   BaseCrudDao<String, E, T>()`, with `class OrderDao : AbstractTenantDao<Order, Orders>()`
     *   below it. The direct superclass of `OrderDao` parameterises `AbstractTenantDao`, not
     *   `BaseReadOnlyDao`, so its type arguments are in the wrong positions; `E` and `T` are
     *   substituted as the walk passes through.
     * - **a proxied bean** — a CGLIB subclass generated by Spring inserts a level that parameterises
     *   nothing at all.
     *
     * @param index position in `BaseReadOnlyDao<PK, E, T>`
     * @return the concrete class at that position
     * @throws IllegalStateException when the chain does not resolve to a concrete class — a DAO that
     *   is still generic at that position cannot bind to a table, and saying so beats returning the
     *   erased upper bound and failing later with a confusing column error.
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun daoTypeArgument(index: Int): KClass<*> {
        val resolved = resolveDaoTypeArguments(this::class, emptyMap())
            ?: error("Class [${this::class.qualifiedName}] does not extend ${BaseReadOnlyDao::class.simpleName}.")
        val type = resolved.getOrNull(index)
        val classifier = type?.classifier
        return classifier as? KClass<*> ?: error(
            "Cannot resolve type argument #$index of ${BaseReadOnlyDao::class.simpleName} for DAO " +
                "[${this::class.qualifiedName}]; it resolved to [${type ?: "nothing"}]. A DAO must fix " +
                "all three type arguments (primary key, entity, table) to a concrete type."
        )
    }

    companion object {
        private val log = LogFactory.getLog(BaseReadOnlyDao::class)

        /** Positions in `BaseReadOnlyDao<PK, E, T>`. */
        private const val ENTITY_TYPE_ARGUMENT = 1
        private const val TABLE_TYPE_ARGUMENT = 2

        /** The three meta properties the ktorm `Entity` interface adds, which are not business fields. */
        private val ENTITY_META_PROPERTIES = setOf("entityClass", "properties", "changedProperties")

        /**
         * Property names per class, memoised.
         *
         * A class's property list cannot change at runtime, and every payload query reflects at
         * least twice — once for the table entity and once for the return type — so recomputing it
         * is pure waste on the framework's hottest path. Keyed by [KClass], which is itself
         * canonical per class, so the map is bounded by the number of entity and VO types a
         * deployment actually queries.
         */
        private val propertyNameCache = ConcurrentHashMap<KClass<*>, List<String>>()

        private val businessPropertyNameCache = ConcurrentHashMap<KClass<*>, List<String>>()

        /** All property names declared on [klass]. */
        private fun propertyNamesOf(klass: KClass<*>): List<String> =
            propertyNameCache.getOrPut(klass) { klass.memberProperties.map { it.name } }

        /** Property names of [klass] minus the ktorm `Entity` meta properties. */
        private fun businessPropertyNamesOf(klass: KClass<*>): List<String> =
            businessPropertyNameCache.getOrPut(klass) {
                propertyNamesOf(klass).filter { it !in ENTITY_META_PROPERTIES }
            }

        /**
         * Depth-first search up [klass]'s supertypes for [BaseReadOnlyDao], carrying [substitutions]
         * — that class's own type parameter names bound to the concrete types the level below
         * supplied for them.
         *
         * @return the type arguments [BaseReadOnlyDao] ends up parameterised with, or null when this
         *   branch of the hierarchy does not reach it
         */
        private fun resolveDaoTypeArguments(
            klass: KClass<*>,
            substitutions: Map<String, KType>,
        ): List<KType?>? {
            for (superType in klass.supertypes) {
                val superClass = superType.classifier as? KClass<*> ?: continue
                if (superClass != BaseReadOnlyDao::class && !superClass.isSubclassOf(BaseReadOnlyDao::class)) {
                    continue
                }
                // The supertype's arguments are written in terms of `klass`'s type parameters, so
                // they are resolved against the substitutions gathered on the way here.
                val arguments = superType.arguments.map { argument ->
                    val type = argument.type
                    when (val classifier = type?.classifier) {
                        is KTypeParameter -> substitutions[classifier.name]
                        else -> type
                    }
                }
                if (superClass == BaseReadOnlyDao::class) return arguments
                val next = superClass.typeParameters.map { it.name }.zip(arguments)
                    .mapNotNull { (name, type) -> type?.let { name to it } }
                    .toMap()
                resolveDaoTypeArguments(superClass, next)?.let { return it }
            }
            return null
        }
    }

    /**
     * Returns the set of sortable property names based on [io.kudos.base.query.sort.Sortable] annotations
     * on the entity (PO) bound to the current DAO's table (independent of the VO/PO return type in the request).
     */
    protected fun sortWhitelistFromPo(): Set<String> {
        val ec = table().entityClass ?: return emptySet()
        return sortablePropertyNamesForEntity(ec)
    }

    /**
     * Filters client-supplied sort orders by the [io.kudos.base.query.sort.Sortable] annotations on the PO.
     * Every property used for sorting must have the corresponding annotation on the PO; unannotated entries
     * are logged at WARN (with entity class and property name) and ignored in the query.
     * [whitelist] contains all @Sortable property names on the PO; if the PO has no @Sortable annotations,
     * [whitelist] is empty and all requested sort entries are ignored with a warning.
     */
    protected fun filterOrdersBySortWhitelist(rawOrders: List<Order>?, whitelist: Set<String>): List<Order> {
        val list = rawOrders ?: emptyList()
        val rejected = list.filter { it.property !in whitelist }
        if (rejected.isNotEmpty()) {
            val entityName = table().entityClass?.qualifiedName
                ?: table().entityClass?.simpleName
                ?: "unknown"
            for (order in rejected) {
                log.warn(
                    "Sort property in query request is not annotated with @Sortable on the table entity; ignored: entityClass={0}, property={1}",
                    entityName,
                    order.property
                )
            }
        }
        return list.filter { it.property in whitelist }
    }

    /**
     * Returns the database object that the current table belongs to.
     *
     * @return Database object containing the current table
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    protected fun database(): Database = KudosContextHolder.currentDatabase()

    /**
     * Returns the query source for the table specified by T, on which SQL-like operations can be performed.
     *
     * @return Query source
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    protected fun querySource(): QuerySource = database().from(table())

    /**
     * Returns the entity sequence for the table specified by T, on which collection-like operations can be performed.
     *
     * @return Entity sequence
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    protected fun entitySequence(): EntitySequence<E, T> = database().sequenceOf(table())


    //region Row scope (data permission)

    /**
     * The row-scope predicate for this DAO's entity, or null when the query must be left as written.
     *
     * Null is the answer in every one of these cases, and they are all normal: filtering is switched
     * off, the entity declares no scope, the caller declared system authority, or the subject is
     * unrestricted. See [io.kudos.ability.data.rdb.ktorm.rowscope.RowScopeEnforcer].
     */
    protected fun rowScopeExpr(): ColumnDeclaring<Boolean>? =
        RowScopeEnforcer.current?.predicateFor(table(), entityClass())

    /** ANDs the row scope onto an existing predicate. */
    protected fun withRowScope(base: ColumnDeclaring<Boolean>): ColumnDeclaring<Boolean> {
        val scope = rowScopeExpr() ?: return base
        return base.and(scope)
    }

    /**
     * The predicate a query should actually run with: [base] narrowed by the row scope, either one
     * alone, or null when there is nothing to restrict at all.
     *
     * Every query that builds its own `where` goes through this instead of consulting
     * [rowScopeExpr] itself, so "does this method honour the scope?" has one answer for the whole
     * class rather than one per method. The projection and payload queries used to build their
     * where clauses by hand and silently skipped the scope, which is exactly the failure the
     * feature exists to prevent — a filter that looks applied and is not.
     */
    protected fun scopedWhere(base: ColumnDeclaring<Boolean>?): ColumnDeclaring<Boolean>? {
        val scope = rowScopeExpr()
        return when {
            base != null && scope != null -> base.and(scope)
            base != null -> base
            else -> scope
        }
    }

    /** Applies [scopedWhere] to a ktorm [Query]; a null predicate leaves the query untouched. */
    protected fun Query.whereScoped(base: ColumnDeclaring<Boolean>?): Query =
        scopedWhere(base)?.let { expr -> this.where { expr } } ?: this

    /**
     * The entity sequence every **read** goes through, already narrowed to the rows the subject may
     * see.
     *
     * Deliberately a separate method from [entitySequence] rather than a change to it: Ktorm's
     * `update`/`add` on a sequence do not honour its filter, so silently scoping the sequence every
     * DAO method shares would look like it protected writes while doing nothing. Writes are scoped
     * explicitly at their own call sites instead.
     */
    protected fun readSequence(): EntitySequence<E, T> {
        val scope = rowScopeExpr() ?: return entitySequence()
        return entitySequence().filter { scope }
    }

    //endregion Row scope

    private fun filteredSequence(criteria: Criteria?): EntitySequence<E, T> {
        val seq = readSequence()
        return if (criteria == null) seq
        else seq.filter { CriteriaConverter.convert(criteria, table()) }
    }

    /**
     * Returns the primary key column (kudos table convention: every table has exactly one primary key column named id).
     *
     * @return Primary key column object
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    @Suppress("UNCHECKED_CAST")
    protected fun getPkColumn(): Column<PK> {
        return table().primaryKeys[0] as Column<PK>
    }

    /**
     * Creates a query condition expression.
     *
     * @param column Column object
     * @param operator Operator
     * @param value Value to query
     * @return Column declaration object
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    @Suppress("UNCHECKED_CAST")
    open fun <A : Any> whereExpr(column: Column<A>, operator: OperatorEnum, value: A?): ColumnDeclaring<Boolean>? {
        return SqlWhereExpressionFactory.create(column as Column<Any>, operator, value)
    }

    //region Search

    override fun get(id: PK): E? {
        return readSequence().firstOrNull { getPkColumn() eq id }
    }

    override fun <R : Any> get(id: PK, returnType: KClass<R>?): R? {
        return if (returnType == null || returnType == entityClass()) {
            @Suppress("UNCHECKED_CAST")
            get(id) as R?
        } else {
            val query = querySource()
                .select()
                .whereScoped(getPkColumn().eq(id))
            val columnMap = getColumns(returnType)
            query.forEach { row ->
                val values = columnMap.mapValues { (_, column) -> row[column] }
                return instantiateResultItem(returnType, values)
            }
            null
        }
    }

    /**
     * Queries an entity by its primary key value; the result type may be specified via generics.
     *
     * Shortcut for get(id: PK, returnType: KClass<R>).
     *
     * @param R Type of the returned object
     * @param id Primary key value; must be one of: String, Int, Long
     * @return Result object of the specified type; null if not found
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    inline fun <reified R : Any> getAs(id: PK): R? = get(id, R::class)

    override fun getByIds(ids: Collection<PK>, countOfEachBatch: Int): List<E> {
        if (ids.isEmpty()) return listOf()
        val results = mutableListOf<E>()
        GroupExecutor(ids, countOfEachBatch) { subList ->
            val result = readSequence().filter { getPkColumn().inList(subList) }.toList()
            results.addAll(result)
        }.execute()
        return results
    }

    override fun <T : Any> getByIds(
        ids: Collection<PK>,
        returnItemClass: KClass<T>?,
        countOfEachBatch: Int
    ): List<T> {
        if (ids.isEmpty()) return listOf()
        return if (returnItemClass == null || returnItemClass == entityClass()) {
            @Suppress("UNCHECKED_CAST")
            getByIds(ids, countOfEachBatch = countOfEachBatch) as List<T>
        } else {
            val results = mutableListOf<T>()
            val idProperty = getPkColumn().name.underscoreToHump()
            GroupExecutor(ids, countOfEachBatch) { subList ->
                val criteria = Criteria(idProperty, OperatorEnum.IN, subList)
                val result = search(criteria, returnItemClass)
                results.addAll(result)
            }.execute()
            results
        }
    }

    /**
     * Batch-queries entities by their primary key values.
     *
     * Shortcut for getByIds(vararg ids: PK, returnItemClass: KClass<T>?, countOfEachBatch: Int).
     *
     * @param T Element type of the result list
     * @param ids Primary key collection; element type must be one of: String, Int, Long; returns empty list when empty
     * @param countOfEachBatch Batch size; defaults to 1000
     * @return List of objects of the specified element type; empty list when ids is empty
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    inline fun <reified T : Any> getByIdsAs(ids: Collection<PK>, countOfEachBatch: Int = 1000): List<T> =
        getByIds(ids, T::class, countOfEachBatch)

    //endregion Search

    override fun oneSearch(property: KProperty1<E, *>, value: Any?, vararg orders: Order): List<E> =
        oneSearch(property.name, value, *orders)

    override fun <R> oneSearchProperty(
        property: KProperty1<E, *>,
        value: Any?,
        returnProperty: KProperty1<E, R>,
        vararg orders: Order
    ): List<R> = oneSearchProperty(property.name, value, returnProperty.name, *orders)

    override fun oneSearchProperties(
        property: KProperty1<E, *>,
        value: Any?,
        returnProperties: Collection<KProperty1<E, *>>,
        vararg orders: Order
    ): List<Map<String, *>> = oneSearchProperties(property.name, value, returnProperties.map { it.name }, *orders)

    //region oneSearch

    /**
     * Single-property equality query (string property-name version).
     *
     * @param property Property name
     * @param value Query value
     * @param orders Sort orders
     * @return List of entities matching the condition
     */
    private fun oneSearch(property: String, value: Any?, vararg orders: Order): List<E> {
        return doSearchEntity(mapOf(property to value), null, null, *orders)
    }

    /**
     * Single-property equality query returning only a single property (string property-name version).
     *
     * @param property Query property name
     * @param value Query value
     * @param returnProperty Return property name
     * @param orders Sort orders
     * @return List of values for the specified property
     */
    @Suppress("UNCHECKED_CAST")
    private fun <R> oneSearchProperty(
        property: String,
        value: Any?,
        returnProperty: String,
        vararg orders: Order
    ): List<R> {
        val results = doSearchProperties(mapOf(property to value), null, listOf(returnProperty), null, *orders)
        return results.flatMap { it.values } as List<R>
    }

    /**
     * Single-property equality query returning multiple property maps (string property-name version).
     *
     * @param property Query property name
     * @param value Query value
     * @param returnProperties Return property name collection
     * @param orders Sort orders
     * @return List of multi-property maps
     */
    private fun oneSearchProperties(
        property: String, value: Any?, returnProperties: Collection<String>, vararg orders: Order
    ): List<Map<String, *>> {
        return doSearchProperties(mapOf(property to value), null, returnProperties, null, *orders)
    }

    //endregion oneSearch


    //region allSearch

    override fun allSearch(vararg orders: Order): List<E> {
        return readSequence().sortedBy(*sortBy(*orders)).toList()
    }

    /**
     * Query all rows, returning only a single property (string property-name version).
     *
     * @param returnProperty Return property name
     * @param orders Sort orders
     * @return List of values for the specified property
     */
    @Suppress("UNCHECKED_CAST")
    private fun <R> allSearchProperty(returnProperty: String, vararg orders: Order): List<R> {
        val results = doSearchProperties(null, null, listOf(returnProperty), null, *orders)
        return results.flatMap { it.values } as List<R>
    }

    /**
     * Query all rows, returning multiple property maps (string property-name version).
     *
     * @param returnProperties Return property name collection
     * @param orders Sort orders
     * @return List of multi-property maps
     */
    private fun allSearchPropertiesByNames(
        returnProperties: Collection<String>,
        vararg orders: Order
    ): List<Map<String, *>> {
        return doSearchProperties(null, null, returnProperties, null, *orders)
    }

    override fun <R> allSearchProperty(returnProperty: KProperty1<E, R>, vararg orders: Order): List<R> =
        allSearchProperty(returnProperty.name, *orders)

    override fun allSearchProperties(
        returnProperties: Collection<KProperty1<E, *>>,
        vararg orders: Order
    ): List<Map<String, *>> = allSearchPropertiesByNames(returnProperties.map { it.name }, *orders)

    //endregion allSearch


    //region andSearch

    /**
     * Multi-property AND query (string property-name version) returning an entity list.
     *
     * @param properties Property-name-to-value map
     * @param orders Sort orders
     * @return List of entities matching the condition
     */
    private fun andSearchByNames(properties: Map<String, *>, vararg orders: Order): List<E> {
        return doSearchEntity(properties, AndOrEnum.AND, null, *orders)
    }

    override fun andSearch(properties: Map<KProperty1<E, *>, *>, vararg orders: Order): List<E> =
        andSearchByNames(properties.entries.associate { it.key.name to it.value }, *orders)

    open fun andSearch(
        properties: Map<KProperty1<E, *>, *>,
        whereConditionFactory: ((Column<Any>, Any?) -> ColumnDeclaring<Boolean>?)?,
        vararg orders: Order
    ): List<E> {
        val mapped = properties.entries.associate { it.key.name to it.value }
        return doSearchEntity(mapped, AndOrEnum.AND, whereConditionFactory, *orders)
    }

    //endregion andSearch


    //region orSearch

    /**
     * Multi-property OR query (string property-name version) returning an entity list.
     *
     * @param properties Property-name-to-value map
     * @param orders Sort orders
     * @return List of entities matching the condition
     */
    private fun orSearchByNames(properties: Map<String, *>, vararg orders: Order): List<E> {
        return doSearchEntity(properties, AndOrEnum.OR, null, *orders)
    }

    override fun orSearch(properties: Map<KProperty1<E, *>, *>, vararg orders: Order): List<E> =
        orSearchByNames(properties.entries.associate { it.key.name to it.value }, *orders)

    open fun orSearch(
        properties: Map<KProperty1<E, *>, *>,
        whereConditionFactory: ((Column<Any>, Any?) -> ColumnDeclaring<Boolean>?)?,
        vararg orders: Order
    ): List<E> {
        val mapped = properties.entries.associate { it.key.name to it.value }
        return doSearchEntity(mapped, AndOrEnum.OR, whereConditionFactory, *orders)
    }

    //endregion orSearch


    //region inSearch

    /**
     * IN query (string property-name version) returning an entity list.
     *
     * @param property Property name used in the IN clause
     * @param values IN value collection
     * @param orders Sort orders
     * @return List of entities matching the IN condition
     */
    private fun inSearch(property: String, values: Collection<*>, vararg orders: Order): List<E> {
        // `x IN ()` is not valid SQL, so an empty candidate list has to be answered rather than
        // rendered. Nothing can be a member of an empty set, so the answer is no rows.
        if (values.isEmpty()) return listOf()
        val column = requireNotNull(ColumnHelper.columnOf(table(), property)[property]) {
            "Database column for property [$property] not found."
        }
        EncryptedColumnGuard.checkFilterable(column, OperatorEnum.IN)
        var entitySequence = readSequence().filter { column.inCollection(values) }
        entitySequence = entitySequence.sortedBy(*sortBy(*orders))
        return entitySequence.toList()
    }

    override fun inSearch(property: KProperty1<E, *>, values: Collection<*>, vararg orders: Order): List<E> =
        inSearch(property.name, values, *orders)

    /**
     * IN query returning only a single property (string property-name version).
     *
     * @param property Property name used in the IN clause
     * @param values IN value collection
     * @param returnProperty Return property name
     * @param orders Sort orders
     * @return List of values for the specified property
     */
    private fun inSearchProperty(
        property: String, values: Collection<*>, returnProperty: String, vararg orders: Order
    ): List<*> {
        val results = doInSearchProperties(property, values, listOf(returnProperty), *orders)
        return results.flatMap { it.values }
    }

    /**
     * IN query returning multiple property maps (string property-name version).
     *
     * @param property Property name used in the IN clause
     * @param values IN value collection
     * @param returnProperties Return property name collection
     * @param orders Sort orders
     * @return List of multi-property maps
     */
    private fun inSearchProperties(
        property: String, values: Collection<*>, returnProperties: Collection<String>, vararg orders: Order
    ): List<Map<String, *>> {
        return doInSearchProperties(property, values, returnProperties, *orders)
    }

    override fun inSearchById(values: Collection<PK>, vararg orders: Order): List<E> {
        return inSearch(IDbEntity<PK, E>::id.name, values, *orders)
    }

    override fun inSearchPropertyById(values: Collection<PK>, returnProperty: String, vararg orders: Order): List<*> {
        val results = doInSearchProperties(IDbEntity<PK, E>::id.name, values, listOf(returnProperty), *orders)
        return results.flatMap { it.values }
    }

    @Suppress("UNCHECKED_CAST")
    override fun <R> inSearchPropertyById(
        values: Collection<PK>,
        returnProperty: KProperty1<E, R>,
        vararg orders: Order
    ): List<R> = inSearchPropertyById(values, returnProperty.name, *orders) as List<R>

    override fun inSearchPropertiesById(
        values: Collection<PK>, returnProperties: Collection<String>, vararg orders: Order
    ): List<Map<String, *>> {
        return doInSearchProperties(IDbEntity<PK, E>::id.name, values, returnProperties, *orders)
    }

    //endregion inSearch


    //region search Criteria

    /**
     * Complex-condition query allowing the caller to specify the result wrapper class. Properties that do not
     * match the table entity are ignored.
     *
     * The purpose is to avoid the overhead and boilerplate of converting POs to the required VOs across scenarios.
     *
     * Shortcut for search(criteria: Criteria?, returnItemClass: KClass<T>?, vararg orders: Order).
     *
     * @param T Element type of the result list
     * @param criteria Query condition; null means unconditional query; defaults to null
     * @param orders Sort orders
     * @return List of objects of the specified result type
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    inline fun <reified T : Any> searchAs(
        criteria: Criteria? = null,
        vararg orders: Order
    ): List<T> = search(criteria, T::class, *orders)

    override fun search(criteria: Criteria?, vararg orders: Order): List<E> {
        return searchEntityCriteria(criteria, 0, 0, *orders)
    }

    override fun <T : Any> search(criteria: Criteria?, returnItemClass: KClass<T>?, vararg orders: Order): List<T> {
        return if (returnItemClass == null || returnItemClass == entityClass()) {
            @Suppress("UNCHECKED_CAST")
            if (criteria == null) {
                allSearch(*orders) as List<T>
            } else {
                search(criteria, *orders) as List<T>
            }
        } else {
            searchByCriteria(criteria, returnItemClass, orders = orders)
        }
    }

    /**
     * Criteria query returning only a single property (string property-name version).
     *
     * @param criteria Query condition
     * @param returnProperty Return property name
     * @param orders Sort orders
     * @return List of values for the specified property
     */
    @Suppress("UNCHECKED_CAST")
    private fun <R> searchProperty(criteria: Criteria, returnProperty: String, vararg orders: Order): List<R> {
        val results = searchPropertiesCriteria(criteria, listOf(returnProperty), 0, 0, *orders)
        return results.flatMap { it.values } as List<R>
    }

    override fun <R> searchProperty(
        criteria: Criteria,
        returnProperty: KProperty1<E, R>,
        vararg orders: Order
    ): List<R> =
        searchProperty(criteria, returnProperty.name, *orders)

    /**
     * Criteria query returning multiple property maps (string property-name version).
     *
     * @param criteria Query condition
     * @param returnProperties Return property name collection
     * @param orders Sort orders
     * @return List of multi-property maps
     */
    private fun searchPropertiesByNames(
        criteria: Criteria, returnProperties: Collection<String>, vararg orders: Order
    ): List<Map<String, Any?>> {
        return searchPropertiesCriteria(criteria, returnProperties, 0, 0, *orders)
    }

    override fun searchProperties(
        criteria: Criteria,
        returnProperties: Collection<KProperty1<E, *>>,
        vararg orders: Order
    ): List<Map<String, Any?>> = searchPropertiesByNames(criteria, returnProperties.map { it.name }, *orders)

    //endregion search Criteria


    //region pagingSearch

    /**
     * Criteria paging query returning an entity list.
     *
     * @param criteria Query condition; may be null
     * @param pageNo Page number
     * @param pageSize Page size
     * @param orders Sort orders
     * @return Entity list for the current page
     */
    override fun pagingSearch(criteria: Criteria?, pageNo: Int, pageSize: Int, vararg orders: Order): List<E> {
        return searchEntityCriteria(criteria, pageNo, pageSize, *orders)
    }

    /**
     * Criteria paging query with explicit return type.
     *
     * @param criteria Query condition; may be null
     * @param returnItemClass Result element type; may be null
     * @param pageNo Page number
     * @param pageSize Page size
     * @param orders Sort orders
     * @return List of results of the specified type for the current page
     */
    override fun <T : Any> pagingSearch(
        criteria: Criteria?,
        returnItemClass: KClass<T>?,
        pageNo: Int,
        pageSize: Int,
        vararg orders: Order
    ): List<T> {
        return if (returnItemClass == null || returnItemClass == entityClass()) {
            // Use the table-entity logic
            @Suppress("UNCHECKED_CAST")
            pagingSearch(criteria, pageNo, pageSize, *orders) as List<T>
        } else {
            searchByCriteria(criteria, returnItemClass, pageNo, pageSize, *orders)
        }
    }

    /**
     * Paging query allowing the caller to specify the result wrapper class. Properties that do not match
     * the table entity are ignored.
     *
     * The purpose is to avoid the overhead and boilerplate of converting POs to the required VOs across scenarios.
     *
     * Shortcut for pagingSearch(criteria: Criteria?, returnItemClass: KClass<T>?, pageNo: Int, pageSize: Int, vararg orders: Order).
     *
     * @param T Element type of the result list
     * @param criteria Query condition; null means unconditional query; defaults to null
     * @param pageNo Current page number (1-based)
     * @param pageSize Rows per page
     * @param orders Sort orders
     * @return List of objects of the specified result type
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    inline fun <reified T : Any> pagingSearchAs(
        criteria: Criteria?,
        pageNo: Int,
        pageSize: Int,
        vararg orders: Order
    ): List<T> = pagingSearch(criteria, T::class, pageNo, pageSize, *orders)

    /**
     * Paging query that returns only a single column. Reuses [searchPropertiesCriteria] for the query
     * logic, then uses `flatMap` to flatten `List<Map<String, *>>` into a list of column values.
     *
     * @param R Column value type (caller guarantees type safety at the public API boundary)
     * @param criteria Query condition
     * @param returnProperty Column name to query
     * @param pageNo Page number (1-based)
     * @param pageSize Rows per page
     * @param orders Sort orders
     * @return List of values for that column in the current page
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    @Suppress("UNCHECKED_CAST")
    private fun <R> pagingReturnProperty(
        criteria: Criteria, returnProperty: String, pageNo: Int, pageSize: Int, vararg orders: Order
    ): List<R> {
        val results = searchPropertiesCriteria(criteria, listOf(returnProperty), pageNo, pageSize, *orders)
        return results.flatMap { it.values } as List<R>
    }

    override fun <R> pagingReturnProperty(
        criteria: Criteria,
        returnProperty: KProperty1<E, R>,
        pageNo: Int,
        pageSize: Int,
        vararg orders: Order
    ): List<R> = pagingReturnProperty(criteria, returnProperty.name, pageNo, pageSize, *orders)

    /**
     * Criteria paging query returning multiple property maps (string property-name version).
     *
     * @param criteria Query condition
     * @param returnProperties Return property name collection
     * @param pageNo Page number
     * @param pageSize Page size
     * @param orders Sort orders
     * @return List of multi-property maps for the current page
     */
    private fun pagingReturnPropertiesByNames(
        criteria: Criteria, returnProperties: Collection<String>, pageNo: Int, pageSize: Int, vararg orders: Order
    ): List<Map<String, *>> {
        return searchPropertiesCriteria(criteria, returnProperties, pageNo, pageSize, *orders)
    }

    override fun pagingReturnProperties(
        criteria: Criteria,
        returnProperties: Collection<KProperty1<E, *>>,
        pageNo: Int,
        pageSize: Int,
        vararg orders: Order
    ): List<Map<String, *>> =
        pagingReturnPropertiesByNames(criteria, returnProperties.map { it.name }, pageNo, pageSize, *orders)

    //endregion pagingSearch


    //region payload search

    override fun search(listSearchPayload: ListSearchPayload?): List<*> {
        return search(listSearchPayload, null)
    }

    @Suppress("UNCHECKED_CAST")
    override fun <T : Any> search(listSearchPayload: ListSearchPayload?, returnItemClass: KClass<T>): List<T> {
        require(listSearchPayload?.getReturnProperties().isNullOrEmpty()) {
            "When ListSearchPayload.returnProperties is non-empty, search(payload, returnItemClass) cannot guarantee the result element type."
        }
        return if (listSearchPayload == null) {
            search(criteria = null, returnItemClass = returnItemClass)
        } else if (listSearchPayload is MutableListSearchPayload) {
            val originalReturnEntityClass = listSearchPayload.getReturnEntityClass()
            try {
                listSearchPayload.setReturnEntityClass(returnItemClass)
                search(listSearchPayload) as List<T>
            } finally {
                listSearchPayload.setReturnEntityClass(originalReturnEntityClass)
            }
        } else {
            search(listSearchPayload, null, returnItemClass) as List<T>
        }
    }

    /**
     * Queries (including paging) based on the search payload object. See @see SearchPayload for the detailed rules.
     *
     * When the query logic for the same property is specified in both listSearchPayload and whereConditionFactory,
     * whereConditionFactory takes precedence!
     *
     * @param listSearchPayload Search payload; defaults to null. When null, the result list element type is the PO entity class;
     *   in this case, if whereConditionFactory is supplied, the conditions are combined with AND.
     * @param whereConditionFactory Factory function for where-clause expressions. It can define the query logic for the
     *   listSearchPayload parameters or be entirely custom. When the function returns null, the property in
     *   listSearchPayload is treated with an "equals" operation. Defaults to null.
     * @return Result list — three possible types; see @see SearchPayload
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    @Suppress("UNCHECKED_CAST")
    open fun search(
        listSearchPayload: ListSearchPayload? = null,
        whereConditionFactory: ((Column<Any>, Any?) -> ColumnDeclaring<Boolean>?)? = null,
        returnItemClassOverride: KClass<*>? = null
    ): List<*> {
        // select, where, order, paging
        val prepared = payloadQuery(listSearchPayload, whereConditionFactory, returnItemClassOverride)
        val query = prepared.query
        val returnColumnMap = prepared.returnColumnMap

        // result
        val returnProperties = listSearchPayload?.getReturnProperties() ?: emptyList()
        val effectiveReturnClass = returnItemClassOverride ?: listSearchPayload?.getReturnEntityClass()
        return when {
            returnProperties.isEmpty() -> {
                val beanList = mutableListOf<Any>()
                processResult(query, returnColumnMap).forEach { map ->
                    val bean = if (effectiveReturnClass == null) {
                        val tableEntityClass =
                            requireNotNull(table().entityClass) { "Table is not bound to an entity type; cannot create a return object." }
                        Entity.create(tableEntityClass).also { populateResultItem(it, map) }
                    } else {
                        instantiateResultItem(effectiveReturnClass, map)
                    }
                    beanList.add(bean)
                }
                beanList
            }

            returnProperties.size == 1 -> {
                val mapList = processResult(query, returnColumnMap)
                mapList.flatMap { it.values }
            }

            else -> {
                val mapList = processResult(query, returnColumnMap)
                mapList
            }
        }
    }

    /**
     * Builds the payload query all the way to ready-to-run: select, where, order and paging.
     *
     * Shared by [search], [searchMaps], [searchValues] and [pagingSearchWithTotal] so that each of
     * them queries the same rows for the same payload. Ordering and paging used to live inline in
     * [search], which is why anything else built on the payload either duplicated the rules or
     * quietly disagreed with it.
     *
     * @param listSearchPayload the payload; null skips ordering and paging entirely
     * @param whereConditionFactory business-supplied custom where generator
     * @param returnItemClassOverride explicit return type; takes precedence over the payload's
     * @return the query, its column map, and whether paging was applied
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun payloadQuery(
        listSearchPayload: ListSearchPayload? = null,
        whereConditionFactory: ((Column<Any>, Any?) -> ColumnDeclaring<Boolean>?)? = null,
        returnItemClassOverride: KClass<*>? = null
    ): PayloadQuery {
        val prepared = searchByPayload(listSearchPayload, whereConditionFactory, returnItemClassOverride)
        var query = prepared.query
        var paged = false

        listSearchPayload?.let { payload ->
            // paging (when pageNo is null and unpaged search is disallowed, fall back to page 1)
            val pageNo = payload.pageNo?.let { maxOf(1, it) }
                ?: if (payload.isUnpagedSearchAllowed()) null else 1

            // order (only whitelisted fields participate in sorting; a paged query also gets the
            // primary key appended so its pages partition the result set — see pagedSortOf)
            val allowedOrders = filterOrdersBySortWhitelist(payload.orders, sortWhitelistFromPo()).toTypedArray()
            val sort = if (pageNo == null) sortOf(*allowedOrders) else pagedSortOf(*allowedOrders)
            if (sort.isNotEmpty()) {
                query = query.orderBy(sort)
            }

            pageNo?.let {
                // Both bounds are clamped because the payload is untrusted by design. Ktorm's
                // `limit` silently ignores a non-positive argument, so `pageSize = 0` would drop the
                // LIMIT altogether and fetch the whole table — defeating the very cap
                // getMaxPageSize() exists to impose. The offset is computed in Long and clamped for
                // the same reason: `(pageNo - 1) * pageSize` overflows Int at large page numbers and
                // wraps negative, which ktorm also ignores, handing back page 1 alongside an
                // authoritative total — a paginator that lies.
                val pageSize = (payload.pageSize ?: 10).coerceIn(1, maxOf(1, payload.getMaxPageSize()))
                val offset = ((it - 1).toLong() * pageSize).coerceIn(0L, Int.MAX_VALUE.toLong()).toInt()
                query = query.limit(offset, pageSize)
                paged = true
            }
        }
        return PayloadQuery(query, prepared.returnColumnMap, paged)
    }

    override fun searchMaps(listSearchPayload: ListSearchPayload?): List<Map<String, Any?>> =
        searchMaps(listSearchPayload, null)

    /**
     * [searchMaps] with a business-supplied where generator, mirroring
     * [search]'s `whereConditionFactory` parameter.
     *
     * Without this overload, a query that needs both a custom condition *and* a stated result shape
     * would have to fall back to `search(payload, factory)` and cast its `List<*>` — the very thing
     * the typed methods exist to remove.
     *
     * @param listSearchPayload List search payload
     * @param whereConditionFactory Custom where generator; see [search] for the precedence rules
     * @return One map per row, keyed by property name
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    open fun searchMaps(
        listSearchPayload: ListSearchPayload? = null,
        whereConditionFactory: ((Column<Any>, Any?) -> ColumnDeclaring<Boolean>?)? = null
    ): List<Map<String, Any?>> {
        val prepared = payloadQuery(listSearchPayload, whereConditionFactory)
        return processResult(prepared.query, prepared.returnColumnMap)
    }

    override fun searchValues(listSearchPayload: ListSearchPayload): List<Any?> =
        searchValues(listSearchPayload, null)

    /**
     * [searchValues] with a business-supplied where generator. See [searchMaps] for why the overload
     * exists.
     *
     * @param listSearchPayload List search payload; must carry exactly one `returnProperties` entry
     * @param whereConditionFactory Custom where generator
     * @return The value of that property for each row
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    open fun searchValues(
        listSearchPayload: ListSearchPayload,
        whereConditionFactory: ((Column<Any>, Any?) -> ColumnDeclaring<Boolean>?)? = null
    ): List<Any?> {
        val returnProperties = listSearchPayload.getReturnProperties()
        require(returnProperties != null && returnProperties.size == 1) {
            "searchValues needs exactly one entry in ListSearchPayload.returnProperties to know which " +
                "column's values to return, but got ${returnProperties?.size ?: 0}. Use searchMaps(...) " +
                "for several properties, or search(payload, returnItemClass) for whole objects."
        }
        // A name that is not a property of the entity is silently intersected away upstream, which
        // turns the query into `SELECT *` and the result into one empty map per row — so the caller
        // gets an empty list back from a query that matched plenty of rows. Refusing here is the
        // point of this method existing.
        val property = returnProperties.single()
        require(property in getEntityProperties()) {
            "searchValues was asked for property [$property], which entity " +
                "[${table().entityClass?.simpleName}] does not have. Without this check the query " +
                "would select nothing and hand back an empty list as though no rows matched."
        }
        return searchMaps(listSearchPayload, whereConditionFactory).flatMap { it.values }
    }

    override fun pagingSearchWithTotal(
        criteria: Criteria?,
        pageNo: Int,
        pageSize: Int,
        vararg orders: Order
    ): PagingSearchResult<E> {
        val items = searchEntityCriteria(criteria, pageNo, pageSize, *orders)
        // Same `criteria` object feeds both, so the page and its total cannot describe different
        // conditions — which is the whole reason for handing the caller both at once.
        return PagingSearchResult(items, countByCriteria(criteria))
    }

    override fun <T : Any> pagingSearchWithTotal(
        listSearchPayload: ListSearchPayload,
        returnItemClass: KClass<T>
    ): PagingSearchResult<T> = pagingSearchWithTotal(listSearchPayload, returnItemClass, null)

    /**
     * [pagingSearchWithTotal] with a business-supplied where generator. See [searchMaps] for why the
     * overload exists.
     *
     * @param T Result element type
     * @param listSearchPayload List search payload; `returnProperties` must be empty
     * @param returnItemClass Result element type
     * @param whereConditionFactory Custom where generator; see [search] for the precedence rules
     * @return The page's rows together with the total ignoring pagination
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    open fun <T : Any> pagingSearchWithTotal(
        listSearchPayload: ListSearchPayload,
        returnItemClass: KClass<T>,
        whereConditionFactory: ((Column<Any>, Any?) -> ColumnDeclaring<Boolean>?)? = null
    ): PagingSearchResult<T> {
        require(listSearchPayload.getReturnProperties().isNullOrEmpty()) {
            "When ListSearchPayload.returnProperties is non-empty, pagingSearchWithTotal(payload, returnItemClass) " +
                "cannot guarantee the result element type. Use searchMaps(...) or searchValues(...) instead."
        }
        val prepared = payloadQuery(listSearchPayload, whereConditionFactory, returnItemClass)
        val items = processResult(prepared.query, returnItemClass, prepared.returnColumnMap)
        // `totalRecordsInAllPages` is correct either way and costs a second statement only when it
        // has to: with a LIMIT it issues a count over the same expression, and without one it reads
        // the already-materialised row set's size. Order does not matter — ktorm's QueryRowSet is
        // offline and `size()` does not depend on the cursor.
        return PagingSearchResult(items, prepared.query.totalRecordsInAllPages)
    }

    /** Shortcut for [pagingSearchWithTotal] with the element type supplied as a reified parameter. */
    inline fun <reified T : Any> pagingSearchWithTotalAs(
        listSearchPayload: ListSearchPayload
    ): PagingSearchResult<T> = pagingSearchWithTotal(listSearchPayload, T::class)

    //endregion payload search


    //region aggregate

    /**
     * Counts records based on a Criteria.
     *
     * @param criteria Query condition; may be null
     * @return Record count
     */
    protected fun countByCriteria(criteria: Criteria?): Int =
        if (criteria == null) readSequence().count()
        else filteredSequence(criteria).aggregateColumns { count(getPkColumn()) } ?: 0

    override fun count(searchPayload: ISearchPayload?): Int {
        return count(searchPayload, null)
    }

    /**
     * Counts records.
     *
     * @param searchPayload Search payload; null counts all records. When whereConditionFactory is supplied,
     *   conditions are combined with AND by default.
     * @param whereConditionFactory Factory function for where-clause expressions. It can define the query logic for
     *   the searchPayload parameters or be entirely custom. When the function returns null, properties in searchPayload
     *   are treated with an "equals" operation. Defaults to null.
     * @return Record count
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    open fun count(
        searchPayload: ISearchPayload?,
        whereConditionFactory: ((Column<Any>, Any?) -> ColumnDeclaring<Boolean>?)? = null
    ): Int {
        return searchByPayload(searchPayload, whereConditionFactory).query.totalRecordsInAllPages
    }

    override fun count(criteria: Criteria?): Int = countByCriteria(criteria)

    /**
     * Sum of a property (string property-name version), or null when the query matched no rows —
     * `SUM` over an empty result set is SQL NULL, not zero.
     *
     * @param property Property name
     * @param criteria Query condition; may be null
     * @return Sum result; null when no row matched
     */
    @Suppress("UNCHECKED_CAST")
    private fun sumOrNull(property: String, criteria: Criteria?): Number? =
        filteredSequence(criteria).aggregateColumns {
            sum(ColumnHelper.columnOf(table(), property)[property] as Column<Number>)
        }

    /**
     * Average of a property (string property-name version), or null when the query matched no rows.
     *
     * @param property Property name
     * @param criteria Query condition; may be null
     * @return Average result; null when no row matched
     */
    @Suppress("UNCHECKED_CAST")
    private fun avgOrNull(property: String, criteria: Criteria?): Number? =
        filteredSequence(criteria).aggregateColumns {
            avg(ColumnHelper.columnOf(table(), property)[property] as Column<Number>)
        }

    /**
     * Sum of a property, returning null when the query matched no rows.
     *
     * The non-null [sum] answers 0 for an empty result set, which is the right total but hides the
     * difference between "nothing matched" and "the matching rows summed to zero". Use this overload
     * when that difference matters.
     *
     * @param property Property to sum
     * @param criteria Query condition; null means all rows
     * @return Sum result; null when no row matched
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    open fun sumOrNull(property: KProperty1<E, *>, criteria: Criteria? = null): Number? =
        sumOrNull(property.name, criteria)

    /**
     * Average of a property, returning null when the query matched no rows.
     *
     * Prefer this over [avg], which has to throw on an empty result set: the average of nothing is
     * undefined, and answering 0 would be a wrong number rather than a missing one.
     *
     * @param property Property to average
     * @param criteria Query condition; null means all rows
     * @return Average result; null when no row matched
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    open fun avgOrNull(property: KProperty1<E, *>, criteria: Criteria? = null): Number? =
        avgOrNull(property.name, criteria)

    /**
     * Maximum of a property (string property-name version).
     *
     * @param property Property name
     * @param criteria Query condition; may be null
     * @return Maximum value; null if no data
     */
    @Suppress("UNCHECKED_CAST")
    private fun <R : Comparable<R>> max(property: String, criteria: Criteria?): R? =
        filteredSequence(criteria).aggregateColumns {
            max(ColumnHelper.columnOf(table(), property)[property] as Column<Comparable<Any>>)
        } as R?

    /**
     * Minimum of a property (string property-name version).
     *
     * @param property Property name
     * @param criteria Query condition; may be null
     * @return Minimum value; null if no data
     */
    @Suppress("UNCHECKED_CAST")
    private fun <R : Comparable<R>> min(property: String, criteria: Criteria?): R? =
        filteredSequence(criteria).aggregateColumns {
            min(ColumnHelper.columnOf(table(), property)[property] as Column<Comparable<Any>>)
        } as R?

    /**
     * Sum of a property. An empty result set sums to 0 — the mathematically right answer, and the
     * one the non-null return type can express. Use [sumOrNull] to tell "nothing matched" apart
     * from "the rows summed to zero".
     */
    override fun sum(property: KProperty1<E, *>, criteria: Criteria?): Number =
        sumOrNull(property.name, criteria) ?: 0

    /**
     * Average of a property.
     *
     * @throws IllegalStateException when no row matched. There is no honest non-null answer for the
     *   average of an empty set, and returning 0 would be a wrong number silently entering a
     *   business calculation. Call [avgOrNull] when an empty result is expected.
     */
    override fun avg(property: KProperty1<E, *>, criteria: Criteria?): Number =
        avgOrNull(property.name, criteria) ?: error(
            "avg([${property.name}]) matched no rows on table [${table().tableName}]; the average of " +
                "an empty result set is undefined. Use avgOrNull(...) if that is an expected outcome."
        )

    override fun <R : Comparable<R>> max(property: KProperty1<E, R?>, criteria: Criteria?): R? =
        max(property.name, criteria)

    override fun <R : Comparable<R>> min(property: KProperty1<E, R?>, criteria: Criteria?): R? =
        min(property.name, criteria)

    //endregion aggregate

    /**
     * Translates the business-side [Order] array into a list of ktorm `OrderByExpression`, ready to feed
     * `query.orderBy(...)`.
     *
     * Column name → column object resolves via [ColumnHelper.columnOf]; a missing column throws via
     * `requireNotNull` — typically caused by a misspelled property name or a field not exposed on
     * [io.kudos.ability.data.rdb.ktorm.support.ITable]. Failing fast aids diagnosis.
     *
     * @param orders Sort orders array; empty returns an empty list (query gets no order by)
     * @return List of ktorm sort expressions
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun sortOf(vararg orders: Order): List<OrderByExpression> = orders.map { orderByExpressionOf(it) }

    /** One [Order] as a ktorm sort expression. */
    private fun orderByExpressionOf(order: Order): OrderByExpression {
        val column = columnOfProperty(order.property)
        // Sorting on ciphertext returns rows in an order unrelated to the values; see the guard.
        EncryptedColumnGuard.checkSortable(column)
        return if (order.isAscending()) column.asc() else column.desc()
    }

    private fun columnOfProperty(property: String): Column<Any> =
        requireNotNull(ColumnHelper.columnOf(table(), property)[property]) {
            "Database column for property [$property] not found."
        }

    /**
     * The ordering a **paged** query runs with: the caller's [orders], then the primary key as a
     * tiebreaker.
     *
     * Paging without a total order is not well defined. `LIMIT`/`OFFSET` slice whatever order the
     * database happened to produce, and nothing obliges it to produce the same one twice —
     * PostgreSQL explicitly does not guarantee it, and a plan change under concurrent writes is
     * enough to make a row appear on two pages while another appears on none. Sorting by a
     * non-unique column has the same problem within each group of ties.
     *
     * Appending the primary key makes the order total, so pages partition the result set. It costs
     * nothing when the caller already sorts by the primary key, and is an indexed sort otherwise.
     *
     * @param orders the caller's sort orders
     * @return the sort expressions, ending with the primary key unless it is already among them
     */
    private fun pagedSortOf(vararg orders: Order): List<OrderByExpression> {
        val explicit = orders.map { orderByExpressionOf(it) }
        // A table with no primary key has no tiebreaker to add. That is against this module's
        // conventions and already breaks get/delete, but it must not turn paging — which used to
        // work here, just without a stable order — into an IndexOutOfBoundsException thrown from
        // inside the framework. Say what is wrong and leave the query as the caller wrote it.
        val pkColumn = table().primaryKeys.firstOrNull() ?: run {
            log.warn(
                "Table [{0}] declares no primary key, so a paged query cannot be given a total order; " +
                    "its pages may overlap or skip rows. Declare a primary key, or pass an Order on a " +
                    "unique column.",
                table().tableName,
            )
            return explicit
        }
        val alreadyTotal = orders.any { columnOfProperty(it.property).name == pkColumn.name }
        return if (alreadyTotal) explicit else explicit + pkColumn.asc()
    }

    /**
     * Wraps the [OrderByExpression] list from [sortOf] into the
     * `Array<(T) -> OrderByExpression>` shape required by `EntitySequence.sortedBy(...)` — the closures
     * ignore their input and return the static expressions (required by the ktorm entity-sequence signature).
     *
     * Used by the `EntitySequence` path ([searchEntityCriteria]); the `Query` path uses [sortOf] directly.
     *
     * @param orders Sort orders
     * @return Array of sort functions for ktorm entity sequences
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun sortBy(vararg orders: Order): Array<(T) -> OrderByExpression> = sortByOf(sortOf(*orders))

    /** [sortBy] for the paged sequence path; see [pagedSortOf] for why paging needs a total order. */
    private fun pagedSortBy(vararg orders: Order): Array<(T) -> OrderByExpression> =
        sortByOf(pagedSortOf(*orders))

    private fun sortByOf(expressions: List<OrderByExpression>): Array<(T) -> OrderByExpression> =
        expressions.map { expression -> { _: T -> expression } }.toTypedArray()

    /**
     * Translates a "property name → (operator, value)" map into a ktorm where-clause expression (AND / OR composite).
     *
     * Branch semantics:
     * - `IS_NULL` / `IS_NOT_NULL`: directly use the column null check
     * - Value is null or "": defaults to `column IS NULL`; when `ignoreNull=true`, the decision is delegated to `whereConditionFactory`
     * - Otherwise, [SqlWhereExpressionFactory] generates the expression based on the operator
     * - An explicit `whereConditionFactory` can override the default behavior (used by subclasses for custom conditions)
     *
     * Fallback: if no property produces an expression and a custom factory is provided, iterate over all columns
     * and let the factory "try again for each column", allowing it to derive a condition based on the column name
     * (typical use: column-name suffix conventions).
     *
     * @param propertyMap Property → (operator, value)
     * @param andOr Logical combinator between conditions; null defaults to AND
     * @param ignoreNull Whether to skip a column when its value is null/"" (true: let the factory decide)
     * @param whereConditionFactory Custom condition generator; null uses the default
     * @return Combined condition expression; null when no condition is produced (the caller should skip the where clause)
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    @Suppress("UNCHECKED_CAST")
    protected fun processWhere(
        propertyMap: Map<String, Pair<OperatorEnum, *>>,
        andOr: AndOrEnum?,
        ignoreNull: Boolean = false,
        whereConditionFactory: ((Column<Any>, Any?) -> ColumnDeclaring<Boolean>?)? = null
    ): ColumnDeclaring<Boolean>? {
        val columns = ColumnHelper.columnOf(table(), *propertyMap.keys.toTypedArray())
        val expressions = columns.mapNotNull { (property, column) ->
            val (operator, value) = requireNotNull(propertyMap[property]) {
                "Property [$property] is missing a query operator and value."
            }
            when {
                operator == OperatorEnum.IS_NULL -> column.isNull()
                operator == OperatorEnum.IS_NOT_NULL -> column.isNotNull()
                value == null || value == "" ->
                    if (ignoreNull) whereConditionFactory?.invoke(column, value) else column.isNull()
                whereConditionFactory == null -> SqlWhereExpressionFactory.create(column, operator, value)
                // The factory may decline, in which case this falls back to equality — which an
                // encrypted column cannot answer unless its codec is deterministic.
                else -> whereConditionFactory(column, value) ?: run {
                    EncryptedColumnGuard.checkFilterable(column, OperatorEnum.EQ)
                    column eq value
                }
            }
        }.toMutableList()

        if (expressions.isEmpty() && whereConditionFactory != null) {
            table().columns.mapNotNullTo(expressions) { whereConditionFactory(it as Column<Any>, null) }
        }

        if (expressions.isEmpty()) return null
        val combine: (ColumnDeclaring<Boolean>, ColumnDeclaring<Boolean>) -> ColumnDeclaring<Boolean> =
            if (andOr == AndOrEnum.AND) ColumnDeclaring<Boolean>::and else ColumnDeclaring<Boolean>::or
        return expressions.reduce(combine)
    }

    /**
     * Uses the EntitySequence path to query full entities by a "property = value" map; the operator is fixed
     * to EQ and the combinator is decided by [logic]. Differs from [searchEntityCriteria] in that the input is
     * a property-value map (not a Criteria DSL), translated by [processWhere].
     *
     * @param propertyMap Property → value; null means no where clause
     * @param logic AND / OR combinator
     * @param whereConditionFactory Custom condition generator
     * @param orders Sort orders
     * @return Entity list
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun doSearchEntity(
        propertyMap: Map<String, *>?,
        logic: AndOrEnum?,
        whereConditionFactory: ((Column<Any>, Any?) -> ColumnDeclaring<Boolean>?)? = null,
        vararg orders: Order
    ): List<E> {
        var entitySequence = readSequence()
        propertyMap?.let { map ->
            val propMap = map.mapValues { (_, value) -> OperatorEnum.EQ to value }
            processWhere(propMap, logic, false, whereConditionFactory)?.let { expr ->
                entitySequence = entitySequence.filter { expr }
            }
        }
        return entitySequence.sortedBy(*sortBy(*orders)).toList()
    }

    /**
     * Uses the Query path to query multiple columns by a "property = value" map; the operator is fixed to EQ
     * and the combinator is decided by [logic]. Differs from [doSearchEntity] in that the returned columns
     * are specified by [returnProperties], not the full entity fields.
     *
     * @param propertyMap Property → value; null means no where clause
     * @param logic AND / OR combinator
     * @param returnProperties Column names to return
     * @param whereConditionFactory Custom condition generator
     * @param orders Sort orders
     * @return List of column-name → column-value maps
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun doSearchProperties(
        propertyMap: Map<String, *>?,
        logic: AndOrEnum?,
        returnProperties: Collection<String>,
        whereConditionFactory: ((Column<Any>, Any?) -> ColumnDeclaring<Boolean>?)? = null,
        vararg orders: Order
    ): List<Map<String, *>> {
        // select
        val returnColumnMap = ColumnHelper.columnOf(table(), *returnProperties.toTypedArray())
        var query = querySource().select(returnColumnMap.values)

        // where
        val propExpr = propertyMap?.let { map ->
            val propMap = map.mapValues { (_, value) -> OperatorEnum.EQ to value }
            processWhere(propMap, logic, false, whereConditionFactory)
        }
        query = query.whereScoped(propExpr)

        // order
        query = query.orderBy(sortOf(*orders))

        // result
        return processResult(query, returnColumnMap)
    }

    /**
     * Reassembles ktorm [Query] results into instances of business class [T] according to `returnColumnMap`.
     * Instantiation is delegated to [instantiateResultItem], which supports data classes, Entities, and Maps.
     *
     * @param T Target type
     * @param query A pre-built ktorm query
     * @param returnItemClass Target class KClass
     * @param returnColumnMap Property-name → column map (computed by [getColumns])
     * @return List of deserialized objects
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun <T : Any> processResult(
        query: Query,
        returnItemClass: KClass<T>,
        returnColumnMap: Map<String, Column<Any>>
    ): List<T> {
        val resultList = mutableListOf<T>()
        query.forEach { row ->
            val values = returnColumnMap.mapValues { (_, column) -> row[column] }
            val item = instantiateResultItem(returnItemClass, values)
            resultList.add(item)
        }
        return resultList
    }

    /**
     * Flattens ktorm [Query] results directly into `List<Map<String, *>>` (property name → column value).
     * Uses the "multi-column query without a business type" path to avoid reflection overhead.
     *
     * @param query A pre-built ktorm query
     * @param returnColumnMap Property-name → column map
     * @return One map per row
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun processResult(query: Query, returnColumnMap: Map<String, Column<Any>>): List<Map<String, *>> {
        val returnValues = mutableListOf<Map<String, Any?>>()
        query.forEach { row ->
            val map = returnColumnMap.map { (propName, column) -> propName to row[column] }.toMap()
            returnValues.add(map)
        }
        return returnValues
    }

    /**
     * Multi-column property version of an `IN (...)` query: filters by `property IN values` and returns the
     * columns listed in `returnProperties`.
     *
     * @param property Column name used in the IN clause
     * @param values IN candidate value collection
     * @param returnProperties Column names to return
     * @param orders Sort orders
     * @return List of column-name → column-value maps
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun doInSearchProperties(
        property: String, values: Collection<*>, returnProperties: Collection<String>, vararg orders: Order
    ): List<Map<String, *>> {
        // See [inSearch]: an empty IN list is "no rows", not invalid SQL.
        if (values.isEmpty()) return listOf()
        val column = requireNotNull(ColumnHelper.columnOf(table(), property)[property]) {
            "Database column for property [$property] not found."
        }
        EncryptedColumnGuard.checkFilterable(column, OperatorEnum.IN)
        val returnColumnMap = ColumnHelper.columnOf(table(), *returnProperties.toTypedArray())
        var query = querySource().select(returnColumnMap.values)
        query = query.whereScoped(column.inCollection(values))
        query = query.orderBy(sortOf(*orders))
        return processResult(query, returnColumnMap)
    }

    /**
     * Query via the ktorm EntitySequence path: converts criteria into a sequence filter, then sorts and pages.
     * Returns full entities [E]. Complements [searchByCriteria]'s Query path — the sequence path suits "fetch
     * all fields of the entity".
     *
     * Paging threshold: `pageNo=0 || pageSize=0` means "no paging" — returns everything (drop/take are skipped).
     *
     * @param criteria Query condition; null skips the where clause
     * @param pageNo Page number (1-based; 0 means no paging)
     * @param pageSize Rows per page (0 means no paging)
     * @param orders Sort orders
     * @return Entity list
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun searchEntityCriteria(
        criteria: Criteria?, pageNo: Int = 0, pageSize: Int = 0, vararg orders: Order
    ): List<E> {
        val paged = pageNo != 0 && pageSize != 0
        val sort = if (paged) pagedSortBy(*orders) else sortBy(*orders)
        var entitySequence = filteredSequence(criteria).sortedBy(*sort)
        if (paged) {
            entitySequence = entitySequence.drop((pageNo - 1) * pageSize).take(pageSize)
        }
        return entitySequence.toList()
    }

    /**
     * Multi-column projection query via the ktorm Query path: queries only the columns listed in
     * `returnProperties` and returns a list-of-map. Outperforms [searchEntityCriteria] by reading only the
     * required columns and avoiding the full-row → entity deserialization overhead.
     *
     * @param criteria Query condition
     * @param returnProperties Column names to query
     * @param pageNo Page number (1-based; 0 means no paging)
     * @param pageSize Rows per page
     * @param orders Sort orders
     * @return List of column-name → column-value maps
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun searchPropertiesCriteria(
        criteria: Criteria, returnProperties: Collection<String>,
        pageNo: Int = 0, pageSize: Int = 0, vararg orders: Order
    ): List<Map<String, *>> {
        val returnColumnMap = ColumnHelper.columnOf(table(), *returnProperties.toTypedArray())

        // where, order, paging
        val query = prepareQuery(criteria, returnColumnMap, pageNo, pageSize, *orders)

        // result
        return processResult(query, returnColumnMap)
    }

    /**
     * Selects columns based on [returnItemClass] + queries by criteria + applies paging + deserializes into a
     * list of the target type. Compared with [searchPropertiesCriteria], it adds the deserialization step (→ T);
     * compared with [searchEntityCriteria], the columns are determined by returnItemClass (typical use:
     * a business VO/DTO that differs from the table entity).
     *
     * @param T Target return type
     * @param criteria Query condition
     * @param returnItemClass Target type KClass
     * @param pageNo Page number (1-based; 0 means no paging)
     * @param pageSize Rows per page
     * @param orders Sort orders
     * @return List of objects of the target type
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun <T : Any> searchByCriteria(
        criteria: Criteria?,
        returnItemClass: KClass<T>,
        pageNo: Int = 0,
        pageSize: Int = 0,
        vararg orders: Order
    ): List<T> {
        val returnColumnMap = getColumns(returnItemClass)

        // select, where, order, paging
        val query = prepareQuery(criteria, returnColumnMap, pageNo, pageSize, *orders)

        // result
        return processResult(query, returnItemClass, returnColumnMap)
    }

    /**
     * Unified template for building a ktorm Query: select the specified columns → where (when criteria is non-null)
     * → orderBy → limit. Reused by [searchPropertiesCriteria], [searchByCriteria] and [searchByPayload] to avoid
     * duplicating boilerplate.
     *
     * @param criteria Query condition; null skips the where clause
     * @param returnColumnMap Property-name → column
     * @param pageNo Page number (1-based; 0 means no paging)
     * @param pageSize Rows per page
     * @param orders Sort orders
     * @return The constructed ktorm [Query]
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun prepareQuery(
        criteria: Criteria?,
        returnColumnMap: Map<String, Column<Any>>,
        pageNo: Int = 0,
        pageSize: Int = 0,
        vararg orders: Order
    ): Query {
        var query = querySource().select(returnColumnMap.values)

        // where (the row scope is ANDed in by whereScoped)
        query = query.whereScoped(criteria?.let { CriteriaConverter.convert(it, table()) })

        // order (paged queries get the primary key appended, so pages partition the result set)
        val paged = pageNo != 0 && pageSize != 0
        query = query.orderBy(if (paged) pagedSortOf(*orders) else sortOf(*orders))

        // paging
        if (paged) {
            query = query.limit((pageNo - 1) * pageSize, pageSize)
        }

        return query
    }

    /**
     * Full-featured query entry point built on [ISearchPayload], supporting:
     * - select columns: three-level fallback of payload.returnProperties / payload.returnEntityClass / override
     * - where: three-stage assembly of payload property values + nullProperties + criterions (see [getWherePropertyMap])
     * - order + paging: orders / pageNo / pageSize carried by the payload
     *
     * The most common query entry in the ms-* service layer; the other private search* methods are simplified
     * versions of it for Criteria.
     *
     * Returns the query together with the columns it selects, so the caller can add ordering and
     * paging and then decode the rows. That pairing used to travel as a `List<Any>` of
     * `[Query, Set, Map]` that each caller indexed and cast back — a tuple with no names and no type
     * checking, where reordering the elements would compile fine and fail at runtime.
     *
     * @param searchPayload Business query payload; null degrades to "scan-all + default sort"
     * @param whereConditionFactory Business-supplied custom where generator
     * @param returnItemClassOverride Explicit return type; takes precedence over payload.returnEntityClass
     * @return the built query and its property-name → column map
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun searchByPayload(
        searchPayload: ISearchPayload? = null,
        whereConditionFactory: ((Column<Any>, Any?) -> ColumnDeclaring<Boolean>?)? = null,
        returnItemClassOverride: KClass<*>? = null
    ): PayloadQuery {
        val entityProperties = getEntityProperties()

        // select
        val returnProperties = searchPayload?.getReturnProperties() ?: emptyList()
        val effectiveReturnClass = returnItemClassOverride ?: searchPayload?.getReturnEntityClass()
        val props = returnProperties.ifEmpty {
            effectiveReturnClass?.let { propertyNamesOf(it) } ?: entityProperties
        }
        val returnProps = entityProperties.intersect(props.toSet()) // intersection ensures the queried columns exist
        val returnColumnMap = ColumnHelper.columnOf(table(), *returnProps.toTypedArray())
        var query = querySource().select(returnColumnMap.values)

        // where
        val propMap = if (searchPayload == null) {
            emptyMap()
        } else {
            getWherePropertyMap(searchPayload, entityProperties)
        }
        val andOr = searchPayload?.getAndOr() ?: AndOrEnum.AND
        query = query.whereScoped(processWhere(propMap, andOr, true, whereConditionFactory))

        return PayloadQuery(query, returnColumnMap)
    }

    /**
     * A payload-built query and the columns it selects, kept together because decoding the rows
     * needs both.
     *
     * @param query the built ktorm query, before ordering and paging
     * @param returnColumnMap property name → the column selected for it
     */
    private data class PayloadQuery(
        val query: Query,
        val returnColumnMap: Map<String, Column<Any>>,
        /** Whether a LIMIT was applied, which decides how the total row count has to be obtained. */
        val paged: Boolean = false,
    )

    /**
     * Uses reflection to obtain the property-name list of the entity class bound to the table. The three meta
     * properties built into the ktorm Entity interface (`entityClass` / `properties` / `changedProperties`)
     * are filtered out so they are not treated as business fields.
     *
     * @return List of business property names on the entity
     * @throws IllegalArgumentException If the table is not bound to an entity type
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    protected fun getEntityProperties(): List<String> {
        val tableEntityClass = requireNotNull(table().entityClass) { "Table is not bound to an entity type; cannot extract entity properties." }
        return businessPropertyNamesOf(tableEntityClass)
    }

    /**
     * Decomposes [ISearchPayload] into a "column name → (operator, value)" map ready to feed [processWhere].
     *
     * Three-stage assembly:
     * 1. Bean properties of the payload + explicit operator map → default EQ
     * 2. Columns marked by nullProperties: only add `IS_NULL` when the value is absent from the bean (avoids
     *    conflicting with the "value present but null" semantics)
     * 3. Criterions carried by the payload (OR / composite): appended and overriding — business-supplied entries
     *    have the highest priority
     *
     * @param searchPayload Query payload passed from the business side
     * @param entityProperties Legal property list of the current table entity (used as a whitelist filter)
     * @return Map of column name → (operator, value)
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    protected fun getWherePropertyMap(
        searchPayload: ISearchPayload, entityProperties: List<String>
    ): Map<String, Pair<OperatorEnum, *>> {
        val operatorByNameMap = searchPayload.getOperators()
            ?.entries
            ?.associate { it.key.name to it.value }
            ?: emptyMap()
        val propNameAndValueMap = BeanKit.extract(searchPayload)
            .filterKeys { it != "class" }
            .filter { entityProperties.contains(it.key) }
        val resultMap = mutableMapOf<String, Pair<OperatorEnum, *>>()
        propNameAndValueMap.forEach { (propName, value) ->
            var operator = operatorByNameMap[propName]
            if (operator == null) {
                operator = OperatorEnum.EQ
            }
            resultMap[propName] = Pair(operator, value)
        }
        val nullProperties = searchPayload.getNullProperties()
        if (!nullProperties.isNullOrEmpty()) {
            nullProperties.forEach { propName ->
                if (propNameAndValueMap[propName] == null) {
                    resultMap[propName] = Pair(OperatorEnum.IS_NULL, null)
                }
            }
        }
        val criterions = searchPayload.getCriterions()
        if (!criterions.isNullOrEmpty()) {
            criterions.forEach {
                resultMap[it.property] = Pair(it.operator, it.value)
            }
        }
        return resultMap
    }

    /**
     * Intersects the properties reflected from returnType with the table entity properties, then produces a
     * ktorm Column map for subsequent select operations.
     *
     * The intersection is a defensive design: returnType may be a VO/DTO with extra or missing fields. Forcing
     * such columns into ktorm would error out. The intersection guarantees the queried columns exist on the
     * table; extra fields will be ignored or left empty by the caller during the mapTo stage.
     *
     * @param returnType Target return type
     * @return Map of property name → column
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    protected fun getColumns(returnType: KClass<*>): Map<String, Column<Any>> {
        val entityProperties = getEntityProperties()
        val properties = propertyNamesOf(returnType)
        val returnProps = entityProperties.intersect(properties.toSet()) // intersection ensures the queried columns exist
        return ColumnHelper.columnOf(table(), *returnProps.toTypedArray())
    }

    /**
     * Populates a target instance from a QueryRowSet using the column map.
     *
     * @param rowSet QueryRowSet
     * @param destClass Target type
     * @param defaultValues Optional: property name -> default value (e.g. "" for id)
     * @param extraColumns Optional: column info outside the primary table (e.g. joined-table columns), property name -> column;
     *   merged with getColumns, extraColumns takes precedence; passing null is equivalent to an empty Map
     */
    protected fun <R : Any> mapTo(
        rowSet: QueryRowSet,
        destClass: KClass<R>,
        defaultValues: Map<String, Any>? = null,
        extraColumns: Map<String, Column<Any>>? = null
    ): R {
        val columnMap = getColumns(destClass)
        val extras = extraColumns ?: emptyMap()
        val values = (columnMap + extras).mapValues { (_, column) -> rowSet[column] }
        return instantiateResultItem(destClass, values, defaultValues ?: emptyMap())
    }

    /**
     * Deserializes Query-row column values into a [destClass] instance.
     *
     * Three strategies:
     * 1. **Ktorm Entity interface type** (`destClass.isSubclassOf(Entity::class)`): use `Entity.create` +
     *    [populateResultItem] — a Ktorm Entity interface PO has no Kotlin constructor and must go through the proxy factory
     * 2. **Traditional JavaBean / plain Kotlin class**: find the no-arg constructor + property backfill
     * 3. **data class / primary-constructor-only**: inject parameters via [callBy]; missing required non-null fields throw
     *
     * @param R Target type
     * @param destClass Target class
     * @param propertyValues Column name → column value
     * @param defaultValues Column name → default value (e.g. "" for id); lower priority than propertyValues
     * @return The deserialized instance
     * @throws IllegalArgumentException When required fields are missing
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun <R : Any> instantiateResultItem(
        destClass: KClass<R>,
        propertyValues: Map<String, Any?>,
        defaultValues: Map<String, Any?> = emptyMap()
    ): R {
        // Ktorm interface-type POs (companion inherits DbEntityFactory / Entity.Factory) have no Kotlin constructor; must be instantiated via Entity.create.
        if (destClass.isSubclassOf(Entity::class)) {
            @Suppress("UNCHECKED_CAST")
            val entity = Entity.create(destClass as KClass<Entity<*>>) as R
            populateResultItem(entity, defaultValues + propertyValues)
            return entity
        }

        // For traditional JavaBeans / plain Kotlin classes: prefer the no-arg constructor + property backfill.
        destClass.constructors.firstOrNull { it.parameters.isEmpty() }?.let {
            return it.call().also { obj -> populateResultItem(obj, propertyValues) }
        }

        // For immutable types such as data classes: assemble through the primary constructor by parameter name.
        val constructor = requireNotNull(destClass.primaryConstructor) {
            "Class ${destClass.qualifiedName} has neither a no-arg constructor nor a primary constructor; cannot wrap the query result."
        }
        val args = mutableMapOf<KParameter, Any?>()
        val missingRequiredParams = mutableListOf<String>()

        constructor.parameters.forEach { param ->
            val name = param.name ?: return@forEach
            val hasPropertyValue = propertyValues.containsKey(name)
            val hasDefaultValue = defaultValues.containsKey(name)
            if (!hasPropertyValue && !hasDefaultValue) {
                // Non-nullable required constructor parameters without a default must receive a value from the query result.
                if (!param.isOptional && !param.type.isMarkedNullable) {
                    missingRequiredParams.add(name)
                }
                return@forEach
            }
            val value = when {
                hasPropertyValue -> propertyValues[name]
                else -> defaultValues[name]
            }
            // For parameters with a Kotlin default value, passing null overrides the default; skip here so callBy uses the default.
            if (value == null && param.isOptional) {
                return@forEach
            }
            args[param] = value
        }

        require(missingRequiredParams.isEmpty()) {
            "Class ${destClass.qualifiedName} is missing query results for constructor parameters ${missingRequiredParams.joinToString(prefix = "[", postfix = "]")}; cannot instantiate."
        }
        return constructor.callBy(args)
    }

    /**
     * Writes column values back into an already-instantiated object.
     *
     * - **Ktorm Entity**: uses `target[property] = value` so the proxy maintains the changed flag; bypassing the
     *   proxy with direct reflection breaks dirty-field tracking and causes subsequent `update` calls to miss fields
     * - **Plain objects**: uses [BeanKit.setProperty] via the setter
     *
     * @param target Target object
     * @param propertyValues Column name → column value
     * @author K
     * @author AI: Claude
     * @since 1.0.0
     */
    private fun populateResultItem(target: Any, propertyValues: Map<String, Any?>) {
        if (target is Entity<*>) {
            // Ktorm Entity maintains property values through its proxy; use index assignment to keep proxy state.
            propertyValues.forEach { (property, value) ->
                target[property] = value
            }
            return
        }
        // Plain objects still use BeanKit, supporting setter / reflective field writes.
        propertyValues.forEach { (property, value) ->
            BeanKit.setProperty(target, property, value)
        }
    }

}


// Works around ktorm always dispatching to the vararg inList method and its generic-type limitations.
@Suppress("UNCHECKED_CAST")
private fun <T : Any> ColumnDeclaring<T>.inCollection(list: Collection<*>): InListExpression {
    return InListExpression(left = asExpression(), values = list.map { wrapArgument(it as T?) })
}
